'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

module.exports = function authRoutesSource(spec) {
  if (!spec.auth.routesEnabled) return null;
  const paths = filePaths(spec);
  const lines = [
    "'use strict';", '',
    "const express = require('express');",
    'const auth = require(' + js(relativeRequire(paths.authRoutes, paths.auth)) + ');',
    ...(spec.auth.storeEnabled ? ['const store = require(' + js(relativeRequire(paths.authRoutes, paths.authStore)) + ');'] : []),
    '',
    'const router = express.Router();',
    'const config = auth.config;',
    '',
    'function userId(user) { return String(user.id !== undefined ? user.id : user._id); }',
    'function identity(user) { return {userId: userId(user), email: user.email, roles: Array.isArray(user.roles) ? user.roles : []}; }',
    'function validEmail(value) { return typeof value === "string" && /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value); }',
    'function duplicateUser(error) { return error && (error.code === 11000 || error.code === "P2002"); }',
    'function invalidInput(res, message) { return res.status(400).json({error: message}); }',
    '',
    ...(spec.auth.local.enabled && spec.auth.local.allowRegistration ? [
      'router.post(' + js(spec.auth.local.registerPath) + ', async (req, res, next) => {',
      '  try {',
      '    const email = req.body && req.body.email;',
      '    const password = req.body && req.body.password;',
      '    if (!validEmail(email)) return invalidInput(res, "Valid email is required");',
      '    if (typeof password !== "string" || password.length < config.local.passwordMinLength) return invalidInput(res, "Password is too short");',
      '    const existing = await store.findUserByEmail(email);',
      '    if (existing) return res.status(409).json({error: "Account already exists"});',
      '    let user;',
      '    try {',
      '      user = await store.createUser({email, passwordHash: auth.hashPassword(password), roles: config.local.defaultRoles});',
      '    } catch (error) {',
      '      if (duplicateUser(error)) return res.status(409).json({error: "Account already exists"});',
      '      throw error;',
      '    }',
      '    return res.status(201).json(await auth.issueCredentials(identity(user), res));',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    ...(spec.auth.local.enabled ? [
      'router.post(' + js(spec.auth.local.loginPath) + ', async (req, res, next) => {',
      '  try {',
      '    const email = req.body && req.body.email;',
      '    const password = req.body && req.body.password;',
      '    if (!validEmail(email) || typeof password !== "string") return res.status(401).json({error: "Invalid credentials"});',
      '    const user = await store.findUserByEmail(email);',
      '    if (!user || !auth.verifyPassword(password, user.passwordHash)) return res.status(401).json({error: "Invalid credentials"});',
      '    return res.status(200).json(await auth.issueCredentials(identity(user), res));',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    ...(spec.auth.jwt.refresh.enabled ? [
      'router.post(' + js(spec.auth.jwt.refresh.path) + ', async (req, res, next) => {',
      '  try {',
      '    const cookies = auth.parseCookies(req);',
      '    const token = req.body && req.body.refreshToken || cookies[config.jwt.refresh.cookieName];',
      '    return res.status(200).json(await auth.rotateRefreshToken(token, res));',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    ...((spec.auth.local.enabled || spec.auth.session.enabled || spec.auth.jwt.refresh.enabled) ? [
      'router.post(' + js(spec.auth.local.logoutPath) + ', async (req, res, next) => {',
      '  try {',
      ...(spec.auth.session.enabled || spec.auth.jwt.refresh.enabled ? ['    await auth.revokeRequestTokens(req, res);'] : []),
      '    return res.status(204).end();',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    ...(spec.auth.local.enabled ? [
      'router.post(' + js(spec.auth.local.forgotPasswordPath) + ', async (req, res, next) => {',
      '  try {',
      '    const email = req.body && req.body.email;',
      '    const response = {accepted: true};',
      '    if (!validEmail(email)) return res.status(202).json(response);',
      '    const user = await store.findUserByEmail(email);',
      '    if (!user) return res.status(202).json(response);',
      '    const resetToken = auth.opaqueToken();',
      '    await store.createToken({',
      '      kind: "reset", tokenHash: auth.hashToken(resetToken), userId: userId(user), roles: user.roles || [],',
      '      expiresAt: new Date(Date.now() + config.local.passwordReset.ttlSeconds * 1000), metadata: {email: user.email}',
      '    });',
      '    const baseUrl = config.local.passwordReset.resetUrl;',
      '    const resetUrl = baseUrl ? baseUrl + (baseUrl.includes("?") ? "&" : "?") + "token=" + encodeURIComponent(resetToken) : undefined;',
      '    if (config.local.passwordReset.webhookUrlEnv && process.env[config.local.passwordReset.webhookUrlEnv]) {',
      '      try {',
      '        const delivered = await fetch(process.env[config.local.passwordReset.webhookUrlEnv], {',
      '          method: "POST", headers: {"content-type": "application/json"},',
      '          body: JSON.stringify({email: user.email, token: resetToken, resetUrl})',
      '        });',
      '        if (!delivered.ok) console.error("Password reset webhook failed with status", delivered.status);',
      '      } catch (error) { console.error("Password reset webhook failed", error); }',
      '    }',
      '    if (config.local.passwordReset.exposeToken) response.resetToken = resetToken;',
      '    return res.status(202).json(response);',
      '  } catch (error) { next(error); }',
      '});',
      '',
      'router.post(' + js(spec.auth.local.resetPasswordPath) + ', async (req, res, next) => {',
      '  try {',
      '    const token = req.body && req.body.token;',
      '    const password = req.body && req.body.password;',
      '    if (!token) return invalidInput(res, "Reset token is required");',
      '    if (typeof password !== "string" || password.length < config.local.passwordMinLength) return invalidInput(res, "Password is too short");',
      '    const record = await store.consumeToken("reset", auth.hashToken(token));',
      '    if (!record) return res.status(400).json({error: "Invalid or expired reset token"});',
      '    await store.updateUserPassword(record.userId, auth.hashPassword(password));',
      '    await store.revokeUserTokens(["session", "refresh"], record.userId);',
      '    return res.status(200).json({reset: true});',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    ...(spec.auth.oidc.enabled ? [
      'router.get(' + js(spec.auth.oidc.loginPath) + ', async (req, res, next) => {',
      '  try { return res.redirect(await auth.beginOidc(req, res)); } catch (error) { next(error); }',
      '});',
      '',
      'router.get(' + js(spec.auth.oidc.callbackPath) + ', async (req, res, next) => {',
      '  try {',
      '    const result = await auth.completeOidc(req, res);',
      '    if (config.oidc.successRedirect) return res.redirect(config.oidc.successRedirect);',
      '    return res.status(200).json(result);',
      '  } catch (error) { next(error); }',
      '});',
      ''
    ] : []),
    'module.exports = router;',
    ''
  ];
  return lines.join('\n');
};
