'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

module.exports = function authSource(spec) {
  if (!spec.auth.enabled) return null;

  const paths = filePaths(spec);
  const lines = [
    "'use strict';", '',
    "const crypto = require('node:crypto');",
    ...(spec.auth.jwt.enabled ? ["const jwt = require('jsonwebtoken');"] : []),
    ...(spec.auth.storeEnabled ? [
      'const store = require(' + js(relativeRequire(paths.auth, paths.authStore)) + ');'
    ] : []),
    '',
    'const config = ' + js(spec.auth) + ';',
    'let oidcMetadataPromise = null;',
    'let oidcJwks = null;',
    '',
    'function authError(message, statusCode = 401) {',
    '  const error = new Error(message);',
    '  error.statusCode = statusCode;',
    '  return error;',
    '}',
    '',
    'function normalizeRoles(value) {',
    '  if (Array.isArray(value)) return value.map(String);',
    '  if (typeof value === "string" && value) return value.split(/[ ,]+/).filter(Boolean);',
    '  return [];',
    '}',
    '',
    'function hashToken(value) {',
    '  return crypto.createHash("sha256").update(String(value)).digest("hex");',
    '}',
    '',
    'function opaqueToken() { return crypto.randomBytes(32).toString("base64url"); }',
    '',
    'function safeEqual(left, right) {',
    '  const a = Buffer.from(String(left));',
    '  const b = Buffer.from(String(right));',
    '  return a.length === b.length && crypto.timingSafeEqual(a, b);',
    '}',
    '',
    'function parseCookies(req) {',
    '  const header = req.headers && req.headers.cookie || "";',
    '  const result = {};',
    '  for (const item of header.split(";")) {',
    '    const index = item.indexOf("=");',
    '    if (index < 0) continue;',
    '    const name = item.slice(0, index).trim();',
    '    if (!name) continue;',
    '    try { result[name] = decodeURIComponent(item.slice(index + 1).trim()); } catch { result[name] = item.slice(index + 1).trim(); }',
    '  }',
    '  return result;',
    '}',
    '',
    'function cookieHeader(name, value, options = {}) {',
    '  const parts = [name + "=" + encodeURIComponent(value), "Path=" + (options.path || "/"), "HttpOnly"];',
    '  if (options.maxAge !== undefined) parts.push("Max-Age=" + Math.max(0, Math.floor(options.maxAge)));',
    '  if (options.sameSite) parts.push("SameSite=" + options.sameSite.charAt(0).toUpperCase() + options.sameSite.slice(1));',
    '  if (options.secure) parts.push("Secure");',
    '  return parts.join("; ");',
    '}',
    '',
    'function setCookie(res, name, value, options = {}) {',
    '  const current = res.getHeader && res.getHeader("Set-Cookie");',
    '  const next = cookieHeader(name, value, options);',
    '  if (!res.setHeader) return;',
    '  if (!current) res.setHeader("Set-Cookie", next);',
    '  else res.setHeader("Set-Cookie", Array.isArray(current) ? [...current, next] : [current, next]);',
    '}',
    '',
    'function clearCookie(res, name, options = {}) {',
    '  setCookie(res, name, "", {...options, maxAge: 0});',
    '}',
    '',
    'function hashPassword(password) {',
    '  const salt = crypto.randomBytes(16);',
    '  const derived = crypto.scryptSync(String(password), salt, 64);',
    '  return "scrypt$" + salt.toString("base64url") + "$" + derived.toString("base64url");',
    '}',
    '',
    'function verifyPassword(password, encoded) {',
    '  const parts = String(encoded || "").split("$");',
    '  if (parts.length !== 3 || parts[0] !== "scrypt") return false;',
    '  try {',
    '    const salt = Buffer.from(parts[1], "base64url");',
    '    const expected = Buffer.from(parts[2], "base64url");',
    '    const actual = crypto.scryptSync(String(password), salt, expected.length);',
    '    return expected.length === actual.length && crypto.timingSafeEqual(expected, actual);',
    '  } catch { return false; }',
    '}',
    '',
    'function bearerToken(req) {',
    '  const header = req.headers && req.headers.authorization || "";',
    '  return header.startsWith("Bearer ") ? header.slice(7).trim() : null;',
    '}',
    '',
    ...(spec.auth.jwt.enabled ? [
      'function verifyLocalJwt(token) {',
      '  const options = {algorithms: config.jwt.algorithms};',
      '  if (config.jwt.issuer) options.issuer = config.jwt.issuer;',
      '  if (config.jwt.audience) options.audience = config.jwt.audience;',
      '  const payload = jwt.verify(token, process.env[config.jwt.secretEnv], options);',
      '  return {',
      '    userId: payload[config.jwt.userClaim],',
      '    roles: normalizeRoles(payload[config.jwt.rolesClaim]),',
      '    email: payload.email,',
      '    strategy: "jwt"',
      '  };',
      '}',
      '',
      'function signAccessToken(identity) {',
      '  const payload = {',
      '    [config.jwt.userClaim]: identity.userId,',
      '    [config.jwt.rolesClaim]: identity.roles || []',
      '  };',
      '  if (identity.email) payload.email = identity.email;',
      '  const options = {algorithm: config.jwt.algorithms[0], expiresIn: config.jwt.accessTtlSeconds};',
      '  if (config.jwt.issuer) options.issuer = config.jwt.issuer;',
      '  if (config.jwt.audience) options.audience = config.jwt.audience;',
      '  return jwt.sign(payload, process.env[config.jwt.secretEnv], options);',
      '}',
      ''
    ] : []),
    ...(spec.auth.oidc.enabled ? [
      'async function oidcMetadata() {',
      '  if (!oidcMetadataPromise) {',
      '    oidcMetadataPromise = (async () => {',
      '      const issuerValue = String(config.oidc.issuer);',
      '      const issuer = issuerValue.endsWith("/") ? issuerValue.slice(0, -1) : issuerValue;',
      '      const response = await fetch(issuer + "/.well-known/openid-configuration");',
      '      if (!response.ok) throw authError("OIDC discovery failed", 502);',
      '      return response.json();',
      '    })();',
      '  }',
      '  return oidcMetadataPromise;',
      '}',
      '',
      'async function verifyOidcToken(token) {',
      '  const {createRemoteJWKSet, jwtVerify} = await import("jose");',
      '  const metadata = await oidcMetadata();',
      '  if (!oidcJwks) oidcJwks = createRemoteJWKSet(new URL(metadata.jwks_uri));',
      '  const audience = config.oidc.audience || process.env[config.oidc.clientIdEnv];',
      '  const {payload} = await jwtVerify(token, oidcJwks, {issuer: config.oidc.issuer, audience});',
      '  return {',
      '    userId: payload.sub,',
      '    roles: normalizeRoles(payload[config.oidc.rolesClaim]),',
      '    email: payload.email,',
      '    strategy: "oidc"',
      '  };',
      '}',
      ''
    ] : []),
    ...(spec.auth.storeEnabled ? [
      'async function readStoredToken(kind, rawToken, strategy) {',
      '  if (!rawToken) return null;',
      '  const record = await store.findToken(kind, hashToken(rawToken));',
      '  if (!record) throw authError("Invalid or expired token");',
      '  return {userId: record.userId, roles: normalizeRoles(record.roles), email: record.metadata && record.metadata.email, strategy};',
      '}',
      ''
    ] : []),
    'async function tryStrategy(strategy, req) {',
    '  if (strategy === "jwt" && config.jwt.enabled) {',
    '    const token = bearerToken(req);',
    '    if (!token) return null;',
    '    try { return verifyLocalJwt(token); } catch { throw authError("Invalid or expired token"); }',
    '  }',
    '  if (strategy === "apiKey" && config.apiKey.enabled) {',
    '    const raw = req.headers && req.headers[config.apiKey.header];',
    '    if (!raw) return null;',
    '    for (const definition of config.apiKey.keys) {',
    '      const expected = process.env[definition.env];',
    '      if (expected && safeEqual(raw, expected)) return {userId: definition.userId, roles: definition.roles, strategy: "apiKey"};',
    '    }',
    '    throw authError("Invalid API key");',
    '  }',
    ...(spec.auth.session.enabled ? [
      '  if (strategy === "session" && config.session.enabled) {',
      '    const token = parseCookies(req)[config.session.cookieName];',
      '    if (!token) return null;',
      '    return readStoredToken("session", token, "session");',
      '  }'
    ] : []),
    ...(spec.auth.oidc.enabled ? [
      '  if (strategy === "oidc" && config.oidc.enabled) {',
      '    const token = bearerToken(req);',
      '    if (!token) return null;',
      '    try { return await verifyOidcToken(token); } catch (error) {',
      '      if (error && error.statusCode) throw error;',
      '      throw authError("Invalid OIDC token");',
      '    }',
      '  }'
    ] : []),
    '  return null;',
    '}',
    '',
    'async function readAuth(req, rule = {}) {',
    '  const required = rule.required !== false;',
    '  const allowed = rule.strategies && rule.strategies.length ? rule.strategies : config.strategies;',
    '  let credentialError = null;',
    '  for (const strategy of allowed) {',
    '    try {',
    '      const identity = await tryStrategy(strategy, req);',
    '      if (!identity) continue;',
    '      const roles = rule.roles || [];',
    '      if (roles.length && !roles.every(role => identity.roles.includes(role))) throw authError("Forbidden", 403);',
    '      return identity;',
    '    } catch (error) { credentialError = error; }',
    '  }',
    '  if (credentialError) throw credentialError;',
    '  if (required) throw authError("Authentication required");',
    '  return null;',
    '}',
    '',
    'function authenticate(rule = {required: true}) {',
    '  return async function authenticateRequest(req, res, next) {',
    '    try { req.auth = await readAuth(req, rule); next(); }',
    '    catch (error) { res.status(error.statusCode || 401).json({error: error.message}); }',
    '  };',
    '}',
    '',
    'function requireRoles(roles) {',
    '  return function authorize(req, res, next) {',
    '    if (!req.auth) return res.status(401).json({error: "Authentication required"});',
    '    if (!roles.every(role => req.auth.roles.includes(role))) return res.status(403).json({error: "Forbidden"});',
    '    next();',
    '  };',
    '}',
    '',
    ...(spec.auth.storeEnabled ? [
      'async function createOpaqueRecord(kind, identity, ttlSeconds, metadata = {}) {',
      '  const token = opaqueToken();',
      '  await store.createToken({',
      '    kind, tokenHash: hashToken(token), userId: String(identity.userId), roles: identity.roles || [],',
      '    expiresAt: new Date(Date.now() + ttlSeconds * 1000), metadata: {...metadata, ...(identity.email ? {email: identity.email} : {})}',
      '  });',
      '  return token;',
      '}',
      ''
    ] : []),
    'async function issueCredentials(identity, res) {',
    '  const response = {user: {id: String(identity.userId), roles: identity.roles || [], ...(identity.email ? {email: identity.email} : {})}};',
    ...(spec.auth.jwt.enabled ? [
      '  response.accessToken = signAccessToken(identity);',
      '  response.tokenType = "Bearer";',
      '  response.expiresIn = config.jwt.accessTtlSeconds;'
    ] : []),
    ...(spec.auth.jwt.refresh.enabled ? [
      '  const refreshToken = await createOpaqueRecord("refresh", identity, config.jwt.refresh.ttlSeconds);',
      '  setCookie(res, config.jwt.refresh.cookieName, refreshToken, {path: config.basePath, secure: config.session.secure, sameSite: config.session.sameSite, maxAge: config.jwt.refresh.ttlSeconds});',
      '  if (config.jwt.refresh.returnToken) response.refreshToken = refreshToken;'
    ] : []),
    ...(spec.auth.session.enabled ? [
      '  const sessionToken = await createOpaqueRecord("session", identity, config.session.ttlSeconds);',
      '  setCookie(res, config.session.cookieName, sessionToken, {path: config.session.path, secure: config.session.secure, sameSite: config.session.sameSite, maxAge: config.session.ttlSeconds});'
    ] : []),
    '  return response;',
    '}',
    '',
    ...(spec.auth.jwt.refresh.enabled ? [
      'async function rotateRefreshToken(rawToken, res) {',
      '  if (!rawToken) throw authError("Refresh token required");',
      '  const record = await store.consumeToken("refresh", hashToken(rawToken));',
      '  if (!record) throw authError("Invalid or expired refresh token");',
      '  const identity = {userId: record.userId, roles: normalizeRoles(record.roles), email: record.metadata && record.metadata.email};',
      '  return issueCredentials(identity, res);',
      '}',
      ''
    ] : []),
    ...(spec.auth.session.enabled || spec.auth.jwt.refresh.enabled ? [
      'async function revokeRequestTokens(req, res) {',
      '  const cookies = parseCookies(req);',
      ...(spec.auth.session.enabled ? [
        '  const sessionToken = cookies[config.session.cookieName];',
        '  if (sessionToken) await store.revokeToken("session", hashToken(sessionToken));',
        '  clearCookie(res, config.session.cookieName, {path: config.session.path, secure: config.session.secure, sameSite: config.session.sameSite});'
      ] : []),
      ...(spec.auth.jwt.refresh.enabled ? [
        '  const refreshToken = req.body && req.body.refreshToken || cookies[config.jwt.refresh.cookieName];',
        '  if (refreshToken) await store.revokeToken("refresh", hashToken(refreshToken));',
        '  clearCookie(res, config.jwt.refresh.cookieName, {path: config.basePath, secure: config.session.secure, sameSite: config.session.sameSite});'
      ] : []),
      '}',
      ''
    ] : []),
    ...(spec.auth.oidc.enabled ? [
      'function oidcRedirectUri(req) {',
      '  if (config.oidc.redirectUri) return config.oidc.redirectUri;',
      '  return req.protocol + "://" + req.get("host") + config.oidc.callbackPath;',
      '}',
      '',
      'async function beginOidc(req, res) {',
      '  const metadata = await oidcMetadata();',
      '  const state = opaqueToken();',
      '  const verifier = opaqueToken();',
      '  const challenge = crypto.createHash("sha256").update(verifier).digest("base64url");',
      '  const redirectUri = oidcRedirectUri(req);',
      '  await store.createToken({',
      '    kind: "oidc-state", tokenHash: hashToken(state), userId: "oidc-state", roles: [],',
      '    expiresAt: new Date(Date.now() + 600000), metadata: {verifier, redirectUri}',
      '  });',
      '  setCookie(res, "j2e_oidc_state", state, {path: config.basePath, secure: config.session.secure, sameSite: "lax", maxAge: 600});',
      '  const url = new URL(metadata.authorization_endpoint);',
      '  url.searchParams.set("response_type", "code");',
      '  url.searchParams.set("client_id", process.env[config.oidc.clientIdEnv]);',
      '  url.searchParams.set("redirect_uri", redirectUri);',
      '  url.searchParams.set("scope", config.oidc.scopes.join(" "));',
      '  url.searchParams.set("state", state);',
      '  url.searchParams.set("code_challenge", challenge);',
      '  url.searchParams.set("code_challenge_method", "S256");',
      '  return url.toString();',
      '}',
      '',
      'async function completeOidc(req, res) {',
      '  const state = req.query && req.query.state;',
      '  const code = req.query && req.query.code;',
      '  const cookieState = parseCookies(req).j2e_oidc_state;',
      '  if (!state || !code || !cookieState || !safeEqual(state, cookieState)) throw authError("Invalid OIDC state");',
      '  const stateRecord = await store.consumeToken("oidc-state", hashToken(state));',
      '  if (!stateRecord) throw authError("Expired OIDC state");',
      '  const metadata = await oidcMetadata();',
      '  const body = new URLSearchParams({',
      '    grant_type: "authorization_code", code,',
      '    client_id: process.env[config.oidc.clientIdEnv],',
      '    redirect_uri: stateRecord.metadata.redirectUri,',
      '    code_verifier: stateRecord.metadata.verifier',
      '  });',
      '  if (config.oidc.clientSecretEnv) body.set("client_secret", process.env[config.oidc.clientSecretEnv]);',
      '  const tokenResponse = await fetch(metadata.token_endpoint, {',
      '    method: "POST", headers: {"content-type": "application/x-www-form-urlencoded"}, body',
      '  });',
      '  if (!tokenResponse.ok) throw authError("OIDC token exchange failed", 502);',
      '  const tokens = await tokenResponse.json();',
      '  const identity = await verifyOidcToken(tokens.id_token || tokens.access_token);',
      '  clearCookie(res, "j2e_oidc_state", {path: config.basePath, secure: config.session.secure, sameSite: "lax"});',
      '  return issueCredentials(identity, res);',
      '}',
      ''
    ] : []),
    'module.exports = {',
    '  authenticate, requireRoles, readAuth, hashPassword, verifyPassword, hashToken, opaqueToken, parseCookies,',
    '  setCookie, clearCookie, issueCredentials,',
    ...(spec.auth.jwt.refresh.enabled ? ['  rotateRefreshToken,'] : []),
    ...(spec.auth.session.enabled || spec.auth.jwt.refresh.enabled ? ['  revokeRequestTokens,'] : []),
    ...(spec.auth.oidc.enabled ? ['  beginOidc, completeOidc, verifyOidcToken,'] : []),
    '  config',
    '};',
    ''
  ];

  return lines.join('\n');
};
