'use strict';

const {filePaths, js, joinUrl, relativeRequire} = require('./utils');

// Every supported MongoDB/PostgreSQL CRUD operation uses native Fastify routes.
// Unknown populate paths are rejected before generation to avoid silent data loss.
function eligible(entity, spec) {
  return spec.app.framework === 'fastify' &&
    (spec.database.type === 'mongodb' || spec.database.type === 'postgresql') &&
    (!entity.fields.some(field => field.type === 'file') || spec.storage.enabled) &&
    !Object.values(entity.operations).some(op => op.enabled &&
      (op.populate || []).some(name => !entity.fields.some(field =>
        field.type === 'reference' && field.name === name)));
}

module.exports = function nativeCrudSource(spec) {
  const nativePath = require('node:path').posix.join(spec.generation.paths.source, 'fastify-crud.js');
  const entities = spec.api.rest ? spec.entities.filter(e => eligible(e, spec)) : [];
  const imports = entities.map((entity, index) =>
    'const model' + index + ' = ' +
    (spec.database.type === 'mongodb'
      ? 'require(' + js(relativeRequire(nativePath, filePaths(spec, entity.name).model)) + ')'
      : 'connectDatabase.client[' + js(entity.name[0].toLowerCase() + entity.name.slice(1)) + ']') + ';');
  const config = entities.map((entity, index) => ({
    inbound: spec.entities.flatMap(source => source.fields.filter(field => field.type === 'reference' && field.ref === entity.name).map(field => ({model: source.name, field: field.name, many: Boolean(field.many), onDelete: field.onDelete, softDelete: source.softDelete}))),
    modelIndex: index,
    name: entity.name,
    operations: entity.operations,
    idParam: entity.idParam,
    references: entity.fields.filter(field => field.type === 'reference').map(field => ({name:field.name, many:field.many, required:field.required})),
    hasFiles: entity.fields.some(field => field.type === 'file'),
    hooks: entity.hooks ? {before: entity.hooks.before || {}, after: entity.hooks.after || {}} : null,
    softDelete: entity.softDelete,
    audit: entity.audit,
    base: joinUrl(spec.app.apiPrefix, entity.route),
    fields: Object.fromEntries(entity.fields.map(field => [field.name, {
      type: field.type, required: field.required, enum: field.enum || null
    }]))
  }));
  return [
    "'use strict';",
    ...(spec.auth.enabled ? ['const auth = require(' + js(relativeRequire(nativePath, filePaths(spec).auth)) + ');'] : []),
    ...(spec.storage.enabled ? ['const storage = require(' + js(relativeRequire(nativePath, filePaths(spec).storage)) + ');'] : []),
    ...(spec.cache.enabled ? ['const cache = require(' + js(relativeRequire(nativePath, filePaths(spec).cache)) + ');'] : []),
    ...(spec.database.type === 'mongodb' ? ['const mongoose = require("mongoose");'] : []),
    ...(spec.database.type === 'postgresql'
      ? ['const connectDatabase = require(' + js(relativeRequire(nativePath, filePaths(spec).database)) + ');']
      : []),
    ...(spec.database.type === 'postgresql' ? [
      'const postgresDelete = require(' + js(relativeRequire(nativePath, require('node:path').posix.join(spec.generation.paths.source, 'fastify-postgres-delete.js'))) + ');'
    ] : []),
    ...(spec.database.type === 'mongodb' ? [
      'const mongoDelete = require(' + js(relativeRequire(nativePath, require('node:path').posix.join(spec.generation.paths.source, 'fastify-mongo-delete.js'))) + ');'
    ] : []),
    ...imports,
    ...entities.filter(entity => entity.hooks && entity.hooks.module).map(entity => 'const hooks' + entity.name + ' = require(' + js(relativeRequire(nativePath, entity.hooks.module)) + ');'),
    'const hookModules = {' + entities.filter(entity => entity.hooks && entity.hooks.module).map(entity => js(entity.name) + ': hooks' + entity.name).join(',') + '};',
    ...(spec.database.type === 'mongodb' ? spec.entities.filter(source => !entities.some(entity => entity.name === source.name)).map(source => 'const relationModel' + source.name + ' = require(' + js(relativeRequire(nativePath, filePaths(spec, source.name).model)) + ');') : []),
    'const relationModels = ' + (spec.database.type === 'mongodb' ? '{' + spec.entities.map(source => js(source.name) + ': ' + (entities.some(e => e.name === source.name) ? 'model' + entities.findIndex(e => e.name === source.name) : 'relationModel' + source.name)).join(',') + '}' : '{}') + ';',
    'const config = ' + js(config) + ';',
    'const models = [' + entities.map((unused, i) => 'model' + i).join(', ') + '];',
    'const postgres = ' + (spec.database.type === 'postgresql') + ';',
    'const authEnabled = ' + Boolean(spec.auth.enabled) + ';',
    'const cacheEnabled = ' + Boolean(spec.cache.enabled) + ';',
    'function validId(id) {',
    '  return postgres ? /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id) : /^[0-9a-f]{24}$/i.test(id);',
    '}',
    'function validate(fields, body, partial) {',
    '  const errors = [];',
    '  if (!body || typeof body !== "object" || Array.isArray(body)) return ["Invalid JSON object"];',
    '  for (const [name, field] of Object.entries(fields)) {',
    '    const value = body[name];',
    '    if (!partial && field.required && (value === undefined || value === null)) errors.push(name + " is required");',
    '    if (value == null) continue;',
    '    if (field.type === "string" && typeof value !== "string") errors.push(name + " has an invalid value");',
    '    if (field.type === "number" && (typeof value !== "number" || !Number.isFinite(value))) errors.push(name + " has an invalid value");',
    '    if (field.type === "boolean" && typeof value !== "boolean") errors.push(name + " has an invalid value");',
    '    if (field.type === "date" && Number.isNaN(Date.parse(value))) errors.push(name + " has an invalid value");',
    '    if (field.enum && !field.enum.includes(value)) errors.push(name + " has an invalid value");',
    '  }',
    '  return errors;',
    '}',
    'async function populateRecord(entry, record, fields) {',
    '  if (!record || !fields || !fields.length) return record;',
    '  if (postgres) return models[entry.modelIndex].findUnique({where: {id: record.id}, include: Object.fromEntries(fields.map(name => [name, true]))});',
    '  return models[entry.modelIndex].findById(record._id).populate(fields);',
    '}',
    'function writeData(entry, body, mode) {',
    '  const data = {...body};',
    '  for (const field of entry.references) {',
    '    if (!Object.prototype.hasOwnProperty.call(data, field.name)) continue;',
    '    const reference = data[field.name];',
    '    if (field.many) data[field.name] = { [mode === "create" ? "connect" : "set"]: (Array.isArray(reference) ? reference : []).map(id => ({id})) };',
    '    else if (reference === null) {if (mode === "create") delete data[field.name]; else data[field.name] = {disconnect: true};}',
    '    else data[field.name] = {connect: {id: reference}};',
    '  }',
    '  return data;',
    '}',
    'async function postgresTransaction(entry, enabled, work) {',
    '  if (!enabled) return work(models[entry.modelIndex]);',
    '  for (let attempt = 0; attempt < 3; attempt += 1) {',
    '    try {return await connectDatabase.client.$transaction(async tx => work(tx[entry.name[0].toLowerCase() + entry.name.slice(1)], tx), {isolationLevel: "Serializable"});}',
    '    catch (error) {if (error.code !== "P2034" || attempt === 2) throw error; await new Promise(resolve => setTimeout(resolve, 10 * (attempt + 1)));}',
    '  }',
    '}',
    'async function transactional(enabled, work) {',
    '  if (!enabled || postgres) return work(null);',
    '  const session = await mongoose.startSession();',
    '  try {let result; await session.withTransaction(async () => {result = await work(session);}); return result;}',
    '  finally {await session.endSession();}',
    '}',
    'function liveFilter(entry, filter = {}) {return entry.softDelete.enabled ? {...filter, [entry.softDelete.field]: null} : filter;}',
    'async function callHook(entry, phase, action, request, reply, model, result) {',
    '  const name = entry.hooks && entry.hooks[phase] && entry.hooks[phase][action];',
    '  const callback = name && hookModules[entry.name] && hookModules[entry.name][name];',
    '  if (typeof callback !== "function") return false;',
    '  const req = {body: request.body, params: request.params, query: request.query, headers: request.headers, auth: request.raw.auth, id: request.raw.id};',
    '  const res = {headersSent: false, status(code) {reply.code(code); return this;}, json(body) {this.headersSent = true; reply.send(body); return this;}, send(body) {this.headersSent = true; reply.send(body); return this;}, end() {this.headersSent = true; reply.send(); return this;}};',
    '  await callback({req, res, model, ...(phase === "after" ? {result} : {})});',
    '  request.body = req.body;',
    '  return res.headersSent;',
    '}',
    'module.exports = function registerCrud(fastify) {',
    '  for (const entry of config) {',
    '    const model = models[entry.modelIndex];',
    '    for (const [action, op] of Object.entries(entry.operations)) {',
    '      if (!op.enabled) continue;',
    '      const fullPath = entry.base + (op.path === "/" ? "" : op.path);',
    '      const url = fullPath;',
    '      fastify.route({method: op.method.toUpperCase(), url, handler: async (request, reply) => {',
    '        if (authEnabled && op.auth && op.auth.required) {',
    '          try { request.raw.auth = await auth.readAuth(request.raw, op.auth); }',
    '          catch (error) { return reply.code(error.statusCode || 401).send({error: error.message}); }',
    '        }',
    '        const id = request.params && request.params[entry.idParam];',
    '        if (["get", "update", "delete"].includes(action) && !validId(id)) return reply.code(400).send({error: "Invalid identifier"});',
    '        let storedUploads = [];',
    '        try {',
    '        if (entry.hasFiles && ["create", "update"].includes(action)) {',
    '          const parsed = await storage.parseFastifyMultipart(entry.name, request);',
    '          request.body = parsed.body;',
    '          storedUploads = parsed.stored;',
    '        }',
    '        if (await callHook(entry, "before", action, request, reply, model)) {',
    '          if (storedUploads.length) await storage.cleanup(storedUploads).catch(() => {});',
    '          return;',
    '        }',
    '        if (["create", "update"].includes(action) && op.validate) {',
    '          const errors = validate(entry.fields, request.body, action === "update");',
    '          if (errors.length) {',
    '            if (storedUploads.length) await storage.cleanup(storedUploads).catch(() => {});',
    '            return reply.code(400).send({error: "Invalid request", details: errors});',
    '          }',
    '        }',
    '        const cachePolicy = cacheEnabled && ["list", "get"].includes(action) && op.cache.enabled ? op.cache : null;',
    '        const cacheRequest = {params: request.params, query: request.query, auth: request.raw.auth};',
    '        const cacheEntry = cachePolicy ? await cache.nativeRead(entry.name, action, cachePolicy, cacheRequest) : null;',
    '        if (cacheEntry && cacheEntry.cached !== null) {reply.header("X-Cache", "HIT"); return reply.code(cacheEntry.cached.status).send(cacheEntry.cached.body);}',
    '        if (cacheEntry) reply.header("X-Cache", "MISS");',
    '        if (action === "list") {',
    '          const q = op.query;',
    '          const populate = op.populate || [];',
    '          const conditions = liveFilter(entry);',
    '          for (const field of q.filters || []) {',
    '            if (request.query[field] !== undefined) conditions[field] = request.query[field];',
    '          }',
    '          const p = q.pagination;',
    '          const limit = p.enabled ? Math.min(p.maxLimit, Math.max(1, Number(request.query[p.limitParam]) || p.defaultLimit)) : undefined;',
    '          const page = p.enabled ? Math.max(1, Number(request.query[p.pageParam]) || 1) : 1;',
    '          const sortValue = q.sortParam && request.query[q.sortParam];',
    '          const sortFields = sortValue ? String(sortValue).split(/[ ,]+/).filter(Boolean) : [];',
    '          const orderBy = sortFields.map(field => ({[field.replace(/^-/, "")]: field.startsWith("-") ? "desc" : "asc"}));',
    '          const skip = limit ? (page - 1) * limit : undefined;',
    '          let rows;',
    '          if (postgres) {',
    '            rows = await model.findMany({where: conditions, ...(limit ? {take: limit, skip} : {}), ...(orderBy.length ? {orderBy} : {}), ...(populate.length ? {include: Object.fromEntries(populate.map(name => [name, true]))} : {})});',
    '          } else {',
    '            let query = model.find(conditions);',
    '            if (sortFields.length) query = query.sort(sortFields.join(" "));',
    '            if (limit) query = query.skip(skip).limit(limit);',
    '            if (populate.length) query = query.populate(populate);',
    '            rows = await query.lean();',
    '          }',
    '          const result = entry.hasFiles ? await storage.enrich(entry.name, rows, {protocol: request.protocol, get: name => request.headers[name.toLowerCase()]}) : rows;',
    '          if (await callHook(entry, "after", action, request, reply, model, rows)) return;',
    '          if (cacheEntry) await cache.nativeWrite(cacheEntry.key, result, op.status, cachePolicy.ttlSeconds);',
    '          return reply.code(op.status).send(result);',
    '        }',
    '        if (action === "get") {',
    '          const populate = op.populate || [];',
    '          const record = postgres ? await model.findFirst({where: liveFilter(entry, {id}), ...(populate.length ? {include: Object.fromEntries(populate.map(name => [name, true]))} : {})}) : await (populate.length ? model.findOne(liveFilter(entry, {_id: id})).populate(populate) : model.findOne(liveFilter(entry, {_id: id})));',
    '          if (!record) return reply.code(op.notFoundStatus).send({error: "Not found"});',
    '          const result = entry.hasFiles ? await storage.enrich(entry.name, record, {protocol: request.protocol, get: name => request.headers[name.toLowerCase()]}) : record;',
    '          if (await callHook(entry, "after", action, request, reply, model, record)) return;',
    '          if (cacheEntry) await cache.nativeWrite(cacheEntry.key, result, op.status, cachePolicy.ttlSeconds);',
    '          return reply.code(op.status).send(result);',
    '        }',
    '        if (action === "create") {',
    '          const data = {...request.body};',
    '          if (entry.audit.enabled) {delete data[entry.audit.createdBy]; delete data[entry.audit.updatedBy];}',
    '          if (entry.audit.enabled && request.raw.auth && request.raw.auth.userId) {data[entry.audit.createdBy] = request.raw.auth.userId; data[entry.audit.updatedBy] = request.raw.auth.userId;}',
    '          const record = postgres ? await postgresTransaction(entry, op.transaction, delegate => delegate.create({data: writeData(entry, data, "create")})) : await transactional(op.transaction, async session => (await model.create([data], session ? {session} : {}))[0]);',
    '          const expanded = await populateRecord(entry, record, op.populate);',
    '          const responseRecord = entry.hasFiles ? await storage.enrich(entry.name, expanded, {protocol: request.protocol, get: name => request.headers[name.toLowerCase()]}) : expanded;',
    '          storedUploads = [];',
    '          if (cacheEnabled) await cache.invalidateEntity(entry.name);',
    '          if (await callHook(entry, "after", action, request, reply, model, record)) return;',
    '          return reply.code(op.status).send(responseRecord);',
    '        }',
    '        if (action === "update") {',
    '          const existing = postgres ? await model.findFirst({where: liveFilter(entry, {id})}) : await model.findOne(liveFilter(entry, {_id: id}));',
    '          if (!existing) return reply.code(op.notFoundStatus).send({error: "Not found"});',
    '          const data = {...request.body};',
    '          if (entry.audit.enabled) {delete data[entry.audit.createdBy]; delete data[entry.audit.updatedBy];}',
    '          if (entry.audit.enabled && request.raw.auth && request.raw.auth.userId) data[entry.audit.updatedBy] = request.raw.auth.userId;',
    '          const record = postgres ? await postgresTransaction(entry, op.transaction, async delegate => {if (op.transaction && !await delegate.findFirst({where: liveFilter(entry, {id})})) {const error = new Error("Not found"); error.statusCode = op.notFoundStatus; throw error;} return delegate.update({where: liveFilter(entry, {id}), data: writeData(entry, data, "update")});}) : await transactional(op.transaction, async session => model.findOneAndUpdate(liveFilter(entry, {_id: id}), data, {new: true, runValidators: op.runValidators, ...(session ? {session} : {})}));',
    '          if (entry.hasFiles) await storage.cleanupReplaced(entry.name, existing, request.body);',
    '          const expanded = await populateRecord(entry, record, op.populate);',
    '          const responseRecord = entry.hasFiles ? await storage.enrich(entry.name, expanded, {protocol: request.protocol, get: name => request.headers[name.toLowerCase()]}) : expanded;',
    '          storedUploads = [];',
    '          if (cacheEnabled) await cache.invalidateEntity(entry.name);',
    '          if (await callHook(entry, "after", action, request, reply, model, record)) return;',
    '          return reply.code(op.status).send(responseRecord);',
    '        }',
    '        if (action === "delete") {',
    '          const record = postgres ? await model.findFirst({where: liveFilter(entry, {id})}) : await model.findOne(liveFilter(entry, {_id: id}));',
    '          if (!record) return reply.code(op.notFoundStatus).send({error: "Not found"});',
    '          const deleteResponse = op.status === 204 ? null : (op.populate && op.populate.length ? await populateRecord(entry, record, op.populate) : record);',
    '          if (postgres) {',
    '            try {await postgresTransaction(entry, true, async (delegate, tx) => postgresDelete(tx, entry.name, id));}',
    '            catch (error) {if (error.code === "P2003") return reply.code(409).send({error: "Delete restricted by related records"}); throw error;}',
    '          } else await transactional(op.transaction || entry.inbound.length > 0, session => mongoDelete(relationModels, entry.name, id, session));',
    '          if (entry.hasFiles) await storage.cleanupEntity(entry.name, record);',
    '          if (cacheEnabled) await cache.invalidateEntity(entry.name);',
    '          if (await callHook(entry, "after", action, request, reply, model, record)) return;',
    '          return op.status === 204 ? reply.code(204).send() : reply.code(op.status).send(deleteResponse);',
    '        }',
    '        } catch (error) {',
    '          if (storedUploads.length) await storage.cleanup(storedUploads).catch(() => {});',
    '          if (postgres && error.code === "P2025") return reply.code(op.notFoundStatus || 404).send({error: "Not found"});',
    '          if (error.statusCode && error.statusCode < 500) return reply.code(error.statusCode).send({error: error.message});',
    '          throw error;',
    '        }',
    '      }});',
    '    }',
    '  }',
    '};',
    'module.exports.matches = function matches(method, url) {',
    '  const pathname = String(url).split("?")[0];',
    '  for (const entry of config) for (const op of Object.values(entry.operations)) {',
    '    if (!op.enabled || op.method.toUpperCase() !== String(method).toUpperCase()) continue;',
    '    const pattern = entry.base + (op.path === "/" ? "" : op.path);',
    '    const expected = pattern.split("/").filter(Boolean);',
    '    const actual = pathname.split("/").filter(Boolean);',
    '    if (expected.length === actual.length && expected.every((part, i) => part.startsWith(":") ? actual[i].length > 0 : part === actual[i])) return true;',
    '  }',
    '  return false;',
    '};', ''
  ].join('\n');
};
module.exports.eligible = eligible;
