'use strict';

const {js} = require('./utils');

module.exports = function migrationInitSource(spec) {
  return [
    "'use strict';",
    '',
    "const fs = require('node:fs');",
    "const path = require('node:path');",
    "const {execFileSync} = require('node:child_process');",
    '',
    'const schemaPath = path.resolve(__dirname, "..", ' + js(spec.database.prisma.schemaPath) + ');',
    'const migrationsDir = path.join(path.dirname(schemaPath), "migrations");',
    'const initialDir = path.join(migrationsDir, "00000000000000_init");',
    'const migrationSql = path.join(initialDir, "migration.sql");',
    'const lockFile = path.join(migrationsDir, "migration_lock.toml");',
    '',
    'if (!fs.existsSync(schemaPath)) throw new Error("Prisma schema not found: " + schemaPath);',
    'if (fs.existsSync(migrationsDir) && fs.readdirSync(migrationsDir).length > 0) {',
    '  throw new Error("Refusing to overwrite existing Prisma migrations. Use db:migrate:dev for changes.");',
    '}',
    '',
    'const prismaCli = path.resolve("node_modules", ".bin", process.platform === "win32" ? "prisma.cmd" : "prisma");',
    'if (!fs.existsSync(prismaCli)) throw new Error("Install generated dependencies first: npm install");',
    'const sql = execFileSync(prismaCli, [',
    '  "migrate", "diff", "--from-empty", "--to-schema-datamodel", schemaPath, "--script"',
    '], {cwd: process.cwd(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024});',
    'if (!sql.trim()) throw new Error("Prisma produced an empty initial migration; refusing to write it.");',
    '',
    'fs.mkdirSync(initialDir, {recursive: true});',
    'fs.writeFileSync(migrationSql, sql, {flag: "wx"});',
    'fs.writeFileSync(lockFile, "# Please do not edit this file manually\\nprovider = \\"postgresql\\"\\n", {flag: "wx"});',
    'console.log("Created initial migration at " + migrationSql);',
    'console.log("Review and commit prisma/migrations before deploying. Never edit applied migrations.");',
    ''
  ].join('\n');
};
