'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

module.exports = function observabilitySource(spec) {
  if (!spec.observability.enabled) return null;
  const paths = filePaths(spec);
  const config = spec.observability;

  const lines = [
    "'use strict';", '',
    "const crypto = require('node:crypto');",
    "const {AsyncLocalStorage} = require('node:async_hooks');",
    'const connectDatabase = require(' + js(relativeRequire(paths.observability, paths.database)) + ');',
    ...(spec.outbox.enabled ? [] : []),
    ...(config.metrics.enabled ? ["const client = require('prom-client');"] : []),
    ...(config.tracing.enabled ? [
      "const otel = require('@opentelemetry/api');",
      "const {NodeTracerProvider} = require('@opentelemetry/sdk-trace-node');",
      "const {SimpleSpanProcessor, BatchSpanProcessor, ConsoleSpanExporter, ParentBasedSampler, TraceIdRatioBasedSampler} = require('@opentelemetry/sdk-trace-base');",
      "const {Resource} = require('@opentelemetry/resources');",
      ...(config.tracing.exporter === 'otlp-http'
        ? ["const {OTLPTraceExporter} = require('@opentelemetry/exporter-trace-otlp-http');"]
        : [])
    ] : []),
    '',
    'const config = ' + js(config) + ';',
    "const storage = new AsyncLocalStorage();",
    "const levels = {debug: 10, info: 20, warn: 30, error: 40};",
    'let tracingStarted = false;',
    'let tracerProvider = null;',
    ...(config.tracing.enabled ? ["let tracer = otel.trace.getTracer(" + js(spec.app.packageName) + ");"] : ["let tracer = null;"]),
    '',
    'function contextFields() {',
    '  const current = storage.getStore() || {};',
    '  const fields = {};',
    '  if (current.requestId) fields.requestId = current.requestId;',
    '  if (current.traceId) fields.traceId = current.traceId;',
    '  return fields;',
    '}',
    '',
    'function write(level, event, fields = {}) {',
    '  if (!config.logging.enabled || levels[level] < levels[config.logging.level]) return;',
    '  const record = {time: new Date().toISOString(), level, event, service: ' + js(spec.app.packageName) + ', ...contextFields(), ...fields};',
    '  if (config.logging.format === "json") return console.log(JSON.stringify(record));',
    '  const extra = {...record}; delete extra.time; delete extra.level; delete extra.event;',
    '  console.log("[" + record.time + "] " + level.toUpperCase() + " " + event + " " + JSON.stringify(extra));',
    '}',
    '',
    'const logger = {',
    '  debug: (event, fields) => write("debug", event, fields),',
    '  info: (event, fields) => write("info", event, fields),',
    '  warn: (event, fields) => write("warn", event, fields),',
    '  error: (event, fields) => write("error", event, fields)',
    '};',
    '',
    ...(config.metrics.enabled ? [
      'const registry = new client.Registry();',
      ...(config.metrics.collectDefaultMetrics ? ['client.collectDefaultMetrics({register: registry, prefix: config.metrics.prefix});'] : []),
      'const httpRequests = new client.Counter({name: config.metrics.prefix + "http_requests_total", help: "HTTP requests", labelNames: ["method", "route", "status"], registers: [registry]});',
      'const httpDuration = new client.Histogram({name: config.metrics.prefix + "http_request_duration_seconds", help: "HTTP request duration", labelNames: ["method", "route"], registers: [registry]});',
      'const httpActive = new client.Gauge({name: config.metrics.prefix + "http_active_requests", help: "Active HTTP requests", registers: [registry]});',
      'const graphqlOperations = new client.Counter({name: config.metrics.prefix + "graphql_operations_total", help: "GraphQL operations", labelNames: ["type", "status"], registers: [registry]});',
      'const workflowExecutions = new client.Counter({name: config.metrics.prefix + "workflow_executions_total", help: "Workflow executions", labelNames: ["workflow", "status"], registers: [registry]});',
      'const workflowDuration = new client.Histogram({name: config.metrics.prefix + "workflow_duration_seconds", help: "Workflow duration", labelNames: ["workflow"], registers: [registry]});',
      'const workflowSteps = new client.Counter({name: config.metrics.prefix + "workflow_steps_total", help: "Workflow step executions", labelNames: ["workflow", "action", "status"], registers: [registry]});',
      'const workerRecords = new client.Counter({name: config.metrics.prefix + "worker_records_total", help: "Outbox worker records", labelNames: ["kind", "name", "status"], registers: [registry]});',
      'const outboxPending = new client.Gauge({name: config.metrics.prefix + "outbox_pending", help: "Pending outbox records", registers: [registry]});',
      'const outboxDead = new client.Gauge({name: config.metrics.prefix + "outbox_dead", help: "Dead outbox records", registers: [registry]});'
    ] : [
      'const registry = null;',
      'const httpRequests = null, httpDuration = null, httpActive = null, graphqlOperations = null;',
      'const workflowExecutions = null, workflowDuration = null, workflowSteps = null, workerRecords = null;'
    ]),
    '',
    'async function startTracing() {',
    ...(config.tracing.enabled ? [
      '  if (tracingStarted) return;',
      '  const sampler = new ParentBasedSampler({root: new TraceIdRatioBasedSampler(config.tracing.sampleRate)});',
      '  const resource = new Resource({"service.name": config.tracing.serviceName});',
      '  tracerProvider = new NodeTracerProvider({resource, sampler});',
      ...(config.tracing.exporter === 'console'
        ? ['  tracerProvider.addSpanProcessor(new SimpleSpanProcessor(new ConsoleSpanExporter()));']
        : ['  tracerProvider.addSpanProcessor(new BatchSpanProcessor(new OTLPTraceExporter({url: process.env[config.tracing.endpointEnv]})));']),
      '  tracerProvider.register();',
      '  tracer = otel.trace.getTracer(config.tracing.serviceName);',
      '  tracingStarted = true;',
      '  logger.info("telemetry.tracing.started", {exporter: config.tracing.exporter, sampleRate: config.tracing.sampleRate});'
    ] : ['  tracingStarted = true;']),
    '}',
    '',
    'async function shutdownTracing() {',
    ...(config.tracing.enabled ? [
      '  if (tracerProvider) await tracerProvider.shutdown();',
      '  tracerProvider = null; tracingStarted = false;'
    ] : ['  tracingStarted = false;']),
    '}',
    '',
    'async function withSpan(name, attributes, fn) {',
    ...(config.tracing.enabled ? [
      '  if (!tracer || !tracingStarted) return fn();',
      '  return tracer.startActiveSpan(name, {attributes}, async span => {',
      '    try {',
      '      const result = await fn();',
      '      span.setStatus({code: otel.SpanStatusCode.OK});',
      '      return result;',
      '    } catch (error) {',
      '      span.recordException(error);',
      '      span.setStatus({code: otel.SpanStatusCode.ERROR, message: error.message});',
      '      throw error;',
      '    } finally { span.end(); }',
      '  });'
    ] : ['  return fn();']),
    '}',
    '',
    'function routeLabel(req) {',
    '  if (req.route && req.route.path) return String(req.baseUrl || "") + String(req.route.path);',
    '  if (req.baseUrl) return String(req.baseUrl);',
    '  return req.path || "unknown";',
    '}',
    '',
    'function requestMiddleware(req, res, next) {',
    '  const requestId = req.id || req.headers["x-request-id"] || crypto.randomUUID();',
    '  req.id = requestId;',
    '  res.setHeader("X-Request-Id", requestId);',
    '  const started = process.hrtime.bigint();',
    ...(config.metrics.enabled ? ['  httpActive.inc();'] : []),
    ...(config.tracing.enabled ? [
      '  const span = tracingStarted ? tracer.startSpan("http " + req.method) : null;',
      '  const traceId = span ? span.spanContext().traceId : undefined;',
      '  const activeContext = span ? otel.trace.setSpan(otel.context.active(), span) : null;'
    ] : ['  const span = null;', '  const traceId = undefined;', '  const activeContext = null;']),
    '  let finished = false;',
    '  function finish() {',
    '    if (finished) return; finished = true;',
    '    const duration = Number(process.hrtime.bigint() - started) / 1e9;',
    '    const route = routeLabel(req);',
    ...(config.metrics.enabled ? [
      '    httpActive.dec();',
      '    httpRequests.inc({method: req.method, route, status: String(res.statusCode)});',
      '    httpDuration.observe({method: req.method, route}, duration);'
    ] : []),
    '    const fields = {requestId, method: req.method, route, status: res.statusCode, durationMs: Math.round(duration * 1000)};',
    '    if (req.auth && req.auth.userId) fields.userId = String(req.auth.userId);',
    '    if (req.auth && req.auth.strategy) fields.authStrategy = req.auth.strategy;',
    '    logger.info("http.request.completed", fields);',
    '    if (span) {',
    '      span.setAttribute("http.request.method", req.method);',
    '      span.setAttribute("http.route", route);',
    '      span.setAttribute("http.response.status_code", res.statusCode);',
    '      if (req.auth && req.auth.strategy) span.setAttribute("j2e.auth.strategy", req.auth.strategy);',
    ...(config.tracing.enabled ? [
      '      span.setStatus({code: res.statusCode >= 500 ? otel.SpanStatusCode.ERROR : otel.SpanStatusCode.OK});'
    ] : []),
    '      span.end();',
    '    }',
    '  }',
    '  res.once("finish", finish);',
    '  res.once("close", finish);',
    '  const run = () => storage.run({requestId, traceId}, next);',
    ...(config.tracing.enabled ? ['  return activeContext ? otel.context.with(activeContext, run) : run();'] : ['  return run();']),
    '}',
    '',
    'function recordGraphql(type, status) {',
    ...(config.metrics.enabled ? ['  graphqlOperations.inc({type: type || "unknown", status: status || "ok"});'] : []),
    '}',
    '',
    'async function instrumentWorkflow(name, fn) {',
    '  const started = process.hrtime.bigint();',
    '  return withSpan("workflow " + name, {"j2e.workflow": name}, async () => {',
    '    try {',
    '      const result = await fn();',
    ...(config.metrics.enabled ? ['      workflowExecutions.inc({workflow: name, status: "ok"});'] : []),
    '      return result;',
    '    } catch (error) {',
    ...(config.metrics.enabled ? ['      workflowExecutions.inc({workflow: name, status: "error"});'] : []),
    '      logger.error("workflow.failed", {workflow: name, error: error.message});',
    '      throw error;',
    '    } finally {',
    ...(config.metrics.enabled ? ['      workflowDuration.observe({workflow: name}, Number(process.hrtime.bigint() - started) / 1e9);'] : []),
    '    }',
    '  });',
    '}',
    '',
    'async function instrumentWorkflowStep(workflow, step, action, fn) {',
    '  return withSpan("workflow.step " + workflow + "." + step, {"j2e.workflow": workflow, "j2e.step": step, "j2e.action": action}, async () => {',
    '    try {',
    '      const result = await fn();',
    ...(config.metrics.enabled ? ['      workflowSteps.inc({workflow, action, status: "ok"});'] : []),
    '      return result;',
    '    } catch (error) {',
    ...(config.metrics.enabled ? ['      workflowSteps.inc({workflow, action, status: "error"});'] : []),
    '      throw error;',
    '    }',
    '  });',
    '}',
    '',
    'async function instrumentWorkerRecord(record, fn) {',
    '  const name = String(record.name || "unknown");',
    '  const kind = String(record.kind || "unknown");',
    '  return withSpan("worker " + kind + " " + name, {"j2e.outbox.kind": kind, "j2e.outbox.name": name}, async () => {',
    '    try {',
    '      const result = await fn();',
    ...(config.metrics.enabled ? ['      workerRecords.inc({kind, name, status: "ok"});'] : []),
    '      return result;',
    '    } catch (error) {',
    ...(config.metrics.enabled ? ['      workerRecords.inc({kind, name, status: "error"});'] : []),
    '      logger.error("worker.record.failed", {kind, name, error: error.message});',
    '      throw error;',
    '    }',
    '  });',
    '}',
    '',
    'async function updateOutboxMetrics() {',
    ...(config.metrics.enabled && spec.outbox.enabled ? [
      '  const outbox = require(' + js(relativeRequire(paths.observability, paths.outbox)) + ');',
      '  if (typeof outbox.stats !== "function") return;',
      '  const stats = await outbox.stats();',
      '  outboxPending.set(stats.pending || 0);',
      '  outboxDead.set(stats.dead || 0);'
    ] : []),
    '}',
    '',
    'async function metricsHandler(req, res, next) {',
    '  try {',
    ...(config.metrics.enabled ? [
      '    await updateOutboxMetrics();',
      '    res.setHeader("Content-Type", registry.contentType);',
      '    return res.status(200).send(await registry.metrics());'
    ] : ['    return res.status(404).end();']),
    '  } catch (error) { next(error); }',
    '}',
    '',
    'function livenessHandler(req, res) { return res.status(200).json({status: "alive"}); }',
    '',
    'async function readinessHandler(req, res) {',
    '  const checks = {};',
    '  let ready = true;',
    '  if (config.health.readiness.database) {',
    '    try { await connectDatabase.ping(); checks.database = "ok"; }',
    '    catch (error) { ready = false; checks.database = "error"; logger.error("health.database.failed", {error: error.message}); }',
    '  }',
    ...(spec.outbox.enabled ? [
      '  if (config.health.readiness.outbox) {',
      '    try {',
      '      const outbox = require(' + js(relativeRequire(paths.observability, paths.outbox)) + ');',
      '      checks.outbox = typeof outbox.stats === "function" ? await outbox.stats() : {status: "unknown"};',
      '    } catch (error) { checks.outbox = {status: "error"}; }',
      '  }'
    ] : []),
    '  return res.status(ready ? 200 : 503).json({status: ready ? "ready" : "not_ready", checks});',
    '}',
    '',
    'module.exports = {',
    '  config, logger, storage, startTracing, shutdownTracing, withSpan, requestMiddleware,',
    '  recordGraphql, instrumentWorkflow, instrumentWorkflowStep, instrumentWorkerRecord,',
    '  metricsHandler, livenessHandler, readinessHandler',
    '};',
    ''
  ];

  return lines.join('\n');
};
