'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

function mongoSource(spec) {
  return [
    "'use strict';", '',
    "const mongoose = require('mongoose');", '',
    'const OutboxSchema = new mongoose.Schema({',
    "  kind: {type: String, enum: ['event', 'job'], required: true, index: true},",
    '  name: {type: String, required: true, index: true},',
    "  queue: {type: String, default: 'default', index: true},",
    '  payload: {type: mongoose.Schema.Types.Mixed},',
    "  status: {type: String, enum: ['pending', 'processing', 'done', 'dead'], default: 'pending', index: true},",
    '  attempts: {type: Number, default: 0},',
    '  maxAttempts: {type: Number, required: true},',
    '  backoffMs: {type: Number, required: true},',
    '  availableAt: {type: Date, default: Date.now, index: true},',
    '  lockedAt: {type: Date, default: null},',
    '  lastError: {type: String, default: null}',
    '}, {timestamps: true, versionKey: false});',
    "OutboxSchema.index({status: 1, availableAt: 1, queue: 1});", '',
    "const Outbox = mongoose.model('J2EOutbox', OutboxSchema);", '',
    'async function createRecord(record, session) {',
    '  const documents = await Outbox.create([{',
    '    ...record,',
    '    status: "pending",',
    '    availableAt: record.availableAt || new Date()',
    '  }], session ? {session} : {});',
    '  return documents[0];',
    '}', '',
    'async function enqueueEvent(name, payload, options = {}) {',
    '  return createRecord({',
    '    kind: "event", name, payload, queue: "events",',
    '    maxAttempts: options.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: options.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : options.backoffMs',
    '  }, options.session);',
    '}', '',
    'async function enqueueJob(name, payload, options = {}) {',
    '  const config = options.config || {};',
    '  return createRecord({',
    '    kind: "job", name, payload, queue: config.queue || "default",',
    '    maxAttempts: config.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: config.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : config.backoffMs,',
    '    availableAt: new Date(Date.now() + (options.delayMs || 0))',
    '  }, options.session);',
    '}', '',
    'async function recoverStale() {',
    '  const cutoff = new Date(Date.now() - ' + spec.outbox.lockTimeoutMs + ');',
    '  await Outbox.updateMany({status: "processing", lockedAt: {$lte: cutoff}}, {$set: {status: "pending", lockedAt: null, availableAt: new Date()}});',
    '}', '',
    'async function claimNext(queues = []) {',
    '  const filter = {status: "pending", availableAt: {$lte: new Date()}};',
    '  if (queues.length) filter.queue = {$in: queues};',
    '  return Outbox.findOneAndUpdate(',
    '    filter,',
    '    {$set: {status: "processing", lockedAt: new Date()}},',
    '    {sort: {availableAt: 1, createdAt: 1}, new: true}',
    '  );',
    '}', '',
    'async function markDone(record) {',
    '  await Outbox.updateOne({_id: record._id}, {$set: {status: "done", lockedAt: null, lastError: null}});',
    '}', '',
    'async function retryDead() {',
    '  const result = await Outbox.updateMany({status: "dead"}, {$set: {status: "pending", attempts: 0, lockedAt: null, lastError: null, availableAt: new Date()}});',
    '  return result.modifiedCount || 0;',
    '}', '',
    'async function stats() {',
    '  const [pending, processing, dead] = await Promise.all([',
    '    Outbox.countDocuments({status: "pending"}),',
    '    Outbox.countDocuments({status: "processing"}),',
    '    Outbox.countDocuments({status: "dead"})',
    '  ]);',
    '  return {pending, processing, dead};',
    '}', '',    'async function storageStats() {',
    '  const [pending, processing, dead] = await Promise.all(["pending", "processing", "dead"].map(status => Outbox.countDocuments({queue: "storage", name: "__j2e_storage_cleanup__", status})));',
    '  return {pending, processing, dead};',
    '}',
    'async function retryDeadStorage() {',
    '  const result = await Outbox.updateMany({queue: "storage", name: "__j2e_storage_cleanup__", status: "dead"}, {$set: {status: "pending", attempts: 0, lockedAt: null, lastError: null, availableAt: new Date()}});',
    '  return result.modifiedCount || 0;',
    '}', '',
    'async function storageDead(limit = 20) {',
    '  return Outbox.find({queue: "storage", name: "__j2e_storage_cleanup__", status: "dead"}).sort({updatedAt: -1}).limit(Math.min(100, Math.max(1, limit))).select("_id attempts lastError createdAt updatedAt availableAt").lean();',
    '}', '',

    'async function markFailed(record, error) {',
    '  const attempts = record.attempts + 1;',
    '  const dead = attempts >= record.maxAttempts;',
    '  const delay = record.backoffMs * Math.max(1, Math.pow(2, attempts - 1));',
    '  await Outbox.updateOne({_id: record._id}, {$set: {',
    '    attempts,',
    '    status: dead ? "dead" : "pending",',
    '    lockedAt: null,',
    '    lastError: String(error && error.message || error),',
    '    availableAt: dead ? record.availableAt : new Date(Date.now() + delay)',
    '  }});',
    '}', '',
    'module.exports = {Outbox, claimNext, enqueueEvent, enqueueJob, markDone, markFailed, recoverStale, retryDead, retryDeadStorage, storageDead, stats, storageStats};', ''
  ].join('\n');
}

function postgresSource(spec) {
  const paths = filePaths(spec);
  return [
    "'use strict';", '',
    'const connectDatabase = require(' + js(relativeRequire(paths.outbox, paths.database)) + ');',
    'const prisma = connectDatabase.client;', '',
    'function delegate(db) { return (db || prisma).j2EOutbox; }', '',
    'async function createRecord(record, db) {',
    '  return delegate(db).create({data: {',
    '    ...record,',
    '    payload: record.payload === undefined ? null : record.payload,',
    '    status: "pending",',
    '    availableAt: record.availableAt || new Date()',
    '  }});',
    '}', '',
    'async function enqueueEvent(name, payload, options = {}) {',
    '  return createRecord({',
    '    kind: "event", name, payload, queue: "events",',
    '    maxAttempts: options.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: options.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : options.backoffMs',
    '  }, options.db);',
    '}', '',
    'async function enqueueJob(name, payload, options = {}) {',
    '  const config = options.config || {};',
    '  return createRecord({',
    '    kind: "job", name, payload, queue: config.queue || "default",',
    '    maxAttempts: config.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: config.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : config.backoffMs,',
    '    availableAt: new Date(Date.now() + (options.delayMs || 0))',
    '  }, options.db);',
    '}', '',
    'async function recoverStale() {',
    '  const cutoff = new Date(Date.now() - ' + spec.outbox.lockTimeoutMs + ');',
    '  await prisma.j2EOutbox.updateMany({',
    '    where: {status: "processing", lockedAt: {lte: cutoff}},',
    '    data: {status: "pending", lockedAt: null, availableAt: new Date()}',
    '  });',
    '}', '',
    'async function claimNext(queues = []) {',
    '  for (let attempt = 0; attempt < 8; attempt += 1) {',
    '    const where = {status: "pending", availableAt: {lte: new Date()}};',
    '    if (queues.length) where.queue = {in: queues};',
    '    const candidate = await prisma.j2EOutbox.findFirst({',
    '      where,',
    '      orderBy: [{availableAt: "asc"}, {createdAt: "asc"}]',
    '    });',
    '    if (!candidate) return null;',
    '    const claimed = await prisma.j2EOutbox.updateMany({',
    '      where: {id: candidate.id, status: "pending"},',
    '      data: {status: "processing", lockedAt: new Date()}',
    '    });',
    '    if (claimed.count === 1) return prisma.j2EOutbox.findUnique({where: {id: candidate.id}});',
    '  }',
    '  return null;',
    '}', '',
    'async function markDone(record) {',
    '  await prisma.j2EOutbox.update({',
    '    where: {id: record.id},',
    '    data: {status: "done", lockedAt: null, lastError: null}',
    '  });',
    '}', '',
    'async function retryDead() {',
    '  const result = await prisma.j2EOutbox.updateMany({',
    '    where: {status: "dead"},',
    '    data: {status: "pending", attempts: 0, lockedAt: null, lastError: null, availableAt: new Date()}',
    '  });',
    '  return result.count || 0;',
    '}', '',
    'async function stats() {',
    '  const [pending, processing, dead] = await Promise.all([',
    '    prisma.j2EOutbox.count({where: {status: "pending"}}),',
    '    prisma.j2EOutbox.count({where: {status: "processing"}}),',
    '    prisma.j2EOutbox.count({where: {status: "dead"}})',
    '  ]);',
    '  return {pending, processing, dead};',
    '}', '',    'async function storageStats() {',
    '  const [pending, processing, dead] = await Promise.all(["pending", "processing", "dead"].map(status => prisma.j2EOutbox.count({where: {queue: "storage", name: "__j2e_storage_cleanup__", status}})));',
    '  return {pending, processing, dead};',
    '}',
    'async function retryDeadStorage() {',
    '  const result = await prisma.j2EOutbox.updateMany({where: {queue: "storage", name: "__j2e_storage_cleanup__", status: "dead"}, data: {status: "pending", attempts: 0, lockedAt: null, lastError: null, availableAt: new Date()}});',
    '  return result.count || 0;',
    '}', '',
    'async function storageDead(limit = 20) {',
    '  return prisma.j2EOutbox.findMany({where: {queue: "storage", name: "__j2e_storage_cleanup__", status: "dead"}, orderBy: {updatedAt: "desc"}, take: Math.min(100, Math.max(1, limit)), select: {id:true, attempts:true, lastError:true, createdAt:true, updatedAt:true, availableAt:true}});',
    '}', '',

    'async function markFailed(record, error) {',
    '  const attempts = record.attempts + 1;',
    '  const dead = attempts >= record.maxAttempts;',
    '  const delay = record.backoffMs * Math.max(1, Math.pow(2, attempts - 1));',
    '  await prisma.j2EOutbox.update({',
    '    where: {id: record.id},',
    '    data: {',
    '      attempts,',
    '      status: dead ? "dead" : "pending",',
    '      lockedAt: null,',
    '      lastError: String(error && error.message || error),',
    '      availableAt: dead ? record.availableAt : new Date(Date.now() + delay)',
    '    }',
    '  });',
    '}', '',
    'module.exports = {claimNext, enqueueEvent, enqueueJob, markDone, markFailed, recoverStale, retryDead, stats};', ''
  ].join('\n');
}

module.exports = function outboxSource(spec) {
  return spec.database.type === 'postgresql' ? postgresSource(spec) : mongoSource(spec);
};
