'use strict';

const {js} = require('./utils');

module.exports = function outboxSource(spec) {
  return [
    "'use strict';", '',
    "const mongoose = require('mongoose');", '',
    'const OutboxSchema = new mongoose.Schema({',
    "  kind: {type: String, enum: ['event', 'job'], required: true, index: true},",
    '  name: {type: String, required: true, index: true},',
    "  queue: {type: String, default: 'default', index: true},",
    '  payload: {type: mongoose.Schema.Types.Mixed},',
    "  status: {type: String, enum: ['pending', 'processing', 'done', 'dead'], default: 'pending', index: true},",
    '  attempts: {type: Number, default: 0},',
    '  maxAttempts: {type: Number, required: true},',
    '  backoffMs: {type: Number, required: true},',
    '  availableAt: {type: Date, default: Date.now, index: true},',
    '  lockedAt: {type: Date, default: null},',
    '  lastError: {type: String, default: null}',
    '}, {timestamps: true, versionKey: false});',
    "OutboxSchema.index({status: 1, availableAt: 1, queue: 1});", '',
    "const Outbox = mongoose.model('J2EOutbox', OutboxSchema);", '',
    'async function createRecord(record, session) {',
    '  const documents = await Outbox.create([{',
    '    ...record,',
    '    status: "pending",',
    '    availableAt: record.availableAt || new Date()',
    '  }], session ? {session} : {});',
    '  return documents[0];',
    '}', '',
    'async function enqueueEvent(name, payload, options = {}) {',
    '  return createRecord({',
    '    kind: "event", name, payload, queue: "events",',
    '    maxAttempts: options.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: options.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : options.backoffMs',
    '  }, options.session);',
    '}', '',
    'async function enqueueJob(name, payload, options = {}) {',
    '  const config = options.config || {};',
    '  return createRecord({',
    '    kind: "job", name, payload, queue: config.queue || "default",',
    '    maxAttempts: config.maxAttempts || ' + spec.outbox.maxAttempts + ',',
    '    backoffMs: config.backoffMs === undefined ? ' + spec.outbox.backoffMs + ' : config.backoffMs,',
    '    availableAt: new Date(Date.now() + (options.delayMs || 0))',
    '  }, options.session);',
    '}', '',
    'async function recoverStale() {',
    '  const cutoff = new Date(Date.now() - ' + spec.outbox.lockTimeoutMs + ');',
    '  await Outbox.updateMany({status: "processing", lockedAt: {$lte: cutoff}}, {$set: {status: "pending", lockedAt: null, availableAt: new Date()}});',
    '}', '',
    'async function claimNext(queues = []) {',
    '  const filter = {status: "pending", availableAt: {$lte: new Date()}};',
    '  if (queues.length) filter.queue = {$in: queues};',
    '  return Outbox.findOneAndUpdate(',
    '    filter,'
    '    {$set: {status: "processing", lockedAt: new Date()}},',
    '    {sort: {availableAt: 1, createdAt: 1}, new: true}',
    '  );',
    '}', '',
    'async function markDone(record) {',
    '  await Outbox.updateOne({_id: record._id}, {$set: {status: "done", lockedAt: null, lastError: null}});',
    '}', '',
    'async function retryDead() {',
    '  const result = await Outbox.updateMany({status: "dead"}, {$set: {status: "pending", attempts: 0, lockedAt: null, lastError: null, availableAt: new Date()}});',
    '  return result.modifiedCount || 0;',
    '}', '',
    'async function markFailed(record, error) {',
    '  const attempts = record.attempts + 1;',
    '  const dead = attempts >= record.maxAttempts;',
    '  const delay = record.backoffMs * Math.max(1, Math.pow(2, attempts - 1));',
    '  await Outbox.updateOne({_id: record._id}, {$set: {',
    '    attempts,',
    '    status: dead ? "dead" : "pending",',
    '    lockedAt: null,',
    '    lastError: String(error && error.message || error),',
    '    availableAt: dead ? record.availableAt : new Date(Date.now() + delay)',
    '  }});',
    '}', '',
    'module.exports = {Outbox, claimNext, enqueueEvent, enqueueJob, markDone, markFailed, recoverStale, retryDead};', ''
  ].join('\n');
};
