'use strict';

const {joinUrl} = require('./utils');

function endpointLines(spec) {
  const lines = [];
  if (spec.app.health.enabled) lines.push('- GET ' + spec.app.health.path);
  if (spec.api.graphql.enabled) lines.push('- GET/POST ' + spec.api.graphql.path + ' (GraphQL)');
  if (spec.auth.local.enabled && spec.auth.local.allowRegistration) lines.push('- POST ' + spec.auth.local.registerPath + ' (register)');
  if (spec.auth.local.enabled) {
    lines.push('- POST ' + spec.auth.local.loginPath + ' (login)');
    lines.push('- POST ' + spec.auth.local.forgotPasswordPath + ' (forgot password)');
    lines.push('- POST ' + spec.auth.local.resetPasswordPath + ' (reset password)');
  }
  if (spec.auth.jwt.refresh.enabled) lines.push('- POST ' + spec.auth.jwt.refresh.path + ' (refresh)');
  if (spec.auth.local.enabled || spec.auth.session.enabled || spec.auth.jwt.refresh.enabled) {
    lines.push('- POST ' + spec.auth.local.logoutPath + ' (logout)');
  }
  if (spec.auth.oidc.enabled) {
    lines.push('- GET ' + spec.auth.oidc.loginPath + ' (OIDC login)');
    lines.push('- GET ' + spec.auth.oidc.callbackPath + ' (OIDC callback)');
  }
  if (spec.api.rest) for (const endpoint of spec.endpoints) {
    lines.push('- ' + endpoint.method.toUpperCase() + ' ' + joinUrl(spec.app.apiPrefix, endpoint.path));
  }
  if (spec.api.rest) for (const entity of spec.entities) {
    const base = joinUrl(spec.app.apiPrefix, entity.route);
    for (const operation of Object.values(entity.operations)) {
      if (!operation.enabled) continue;
      const fullPath = operation.path === '/' ? base : joinUrl(base, operation.path);
      lines.push('- ' + operation.method.toUpperCase() + ' ' + fullPath);
    }
  }
  return lines;
}

module.exports = function readmeSource(spec) {
  const databaseLabel = spec.database.type === 'postgresql' ? 'PostgreSQL + Prisma' : 'MongoDB + Mongoose';
  const setup = [
    '    npm install',
    '    cp .env.example .env',
    ...(spec.database.type === 'postgresql' ? ['    npm run db:push'] : []),
    '    npm start'
  ];

  const deployment = [];
  if (spec.outbox.enabled) {
    deployment.push(
      '## Background work', '',
      'Durable events and jobs are backed by the ' + databaseLabel + ' outbox.', '',
      'Worker mode: ' + spec.outbox.worker + '.', '',
      '    npm run worker',
      '    npm run worker:once',
      '    npm run outbox:retry', ''
    );
  }
  if (spec.admin.enabled) {
    deployment.push(
      '## Generated admin UI', '',
      'A standalone React/Vite admin application is generated in ' + spec.admin.outputDir + '.', '',
      '    cd ' + spec.admin.outputDir,
      '    npm install',
      '    npm run dev', '',
      'Production build: npm run build. Override the API URL with VITE_API_BASE_URL when needed.', ''
    );
  }
  if (spec.sdk.enabled) {
    deployment.push(
      '## Generated SDK', '',
      'A standalone API client package is generated in ' + spec.sdk.outputDir + '.', '',
      ...(spec.sdk.languages.includes('javascript') ? ['JavaScript: require("./' + spec.sdk.outputDir + '/javascript")', ''] : []),
      ...(spec.sdk.languages.includes('typescript') ? ['TypeScript: cd ' + spec.sdk.outputDir + ' && npm install && npm run build', ''] : [])
    );
  }
  if (spec.deployment.docker.enabled) {
    deployment.push('## Docker', '', '    docker build -t ' + spec.app.package.name + ' -f ' + spec.deployment.docker.file + ' .', '');
  }
  if (spec.deployment.compose.enabled) {
    deployment.push('## Docker Compose', '', '    docker compose -f ' + spec.deployment.compose.file + ' up --build', '');
  }
  if (spec.deployment.kubernetes.enabled) {
    deployment.push(
      '## Kubernetes', '',
      '1. Copy and fill ' + spec.deployment.kubernetes.directory + '/secret.example.yaml.', '',
      '2. Apply the secret, config, deployment, and service manifests with kubectl.', ''
    );
  }

  return [
    '# ' + spec.app.name, '',
    spec.app.package.description, '',
    'Generated by json-to-express.', '',
    'Database target: ' + databaseLabel + '.', '',
    'API targets: ' + [spec.api.rest ? 'REST' : null, spec.api.graphql.enabled ? 'GraphQL' : null].filter(Boolean).join(' + ') + '.', '',
    ...(spec.auth.enabled ? [
      '## Authentication', '',
      'Enabled strategies: ' + spec.auth.strategies.join(', ') + '.', '',
      ...(spec.auth.local.enabled ? [
        'Local email/password login is generated with scrypt password hashing' +
          (spec.auth.local.allowRegistration ? ', registration' : '') + ', logout, and password reset.', ''
      ] : []),
      ...(spec.auth.jwt.enabled ? [
        'JWT access tokens use ' + spec.auth.jwt.secretEnv + ' and expire after ' + spec.auth.jwt.accessTtlSeconds + ' seconds.', ''
      ] : []),
      ...(spec.auth.jwt.refresh.enabled ? [
        'Refresh tokens are opaque, one-time rotated, stored only as hashes, and expire after ' + spec.auth.jwt.refresh.ttlSeconds + ' seconds.', ''
      ] : []),
      ...(spec.auth.session.enabled ? [
        'Session cookies are durable and backed by the generated database auth-token store.', ''
      ] : []),
      ...(spec.auth.apiKey.enabled ? [
        'API keys are read from the ' + spec.auth.apiKey.header + ' header and configured through environment variables.', ''
      ] : []),
      ...(spec.auth.oidc.enabled ? [
        'OIDC supports discovery, remote JWKS verification, Authorization Code + PKCE login, and bearer verification.', ''
      ] : []),
      'REST and GraphQL apply the same per-operation strategy allowlists and RBAC rules.', ''
    ] : []),
    ...(spec.api.graphql.enabled ? [
      '## GraphQL', '',
      'GraphQL endpoint: ' + spec.api.graphql.path + '.', '',
      'Generated queries use get<Entity> and list<Entities>; mutations use create/update/delete<Entity>.', '',
      'GraphQL exposes a backend-agnostic id: ID! even when the REST target uses MongoDB _id.', ''
    ] : []),
    '## Run', '',
    ...setup, '',
    'Default bind: ' + spec.app.host + ':' + spec.app.port + '.', '',
    ...deployment,
    '## Endpoints', '',
    ...endpointLines(spec), ''
  ].join('\n');
};
