'use strict';

const {joinUrl} = require('./utils');

function endpointLines(spec) {
  const lines = [];
  if (spec.app.health.enabled) lines.push('- GET ' + spec.app.health.path);
  for (const entity of spec.entities) {
    const base = joinUrl(spec.app.apiPrefix, entity.route);
    for (const operation of Object.values(entity.operations)) {
      if (!operation.enabled) continue;
      const fullPath = operation.path === '/' ? base : joinUrl(base, operation.path);
      lines.push('- ' + operation.method.toUpperCase() + ' ' + fullPath);
    }
  }
  return lines;
}

module.exports = function readmeSource(spec) {
  return [
    '# ' + spec.app.name, '',
    spec.app.package.description, '',
    'Generated by json-to-express.', '',
    '## Run', '',
    '    npm install',
    '    cp .env.example .env',
    '    npm start', '',
    'Default bind: ' + spec.app.host + ':' + spec.app.port + '.', '',
    '## Endpoints', '',
    ...endpointLines(spec), ''
  ].join('\n');
};
