'use strict';

const {js} = require('./utils');

module.exports = function storageSource(spec) {
  if (!spec.storage.enabled) return null;

  const definitions = Object.fromEntries(spec.entities.map(entity => [
    entity.name,
    {
      fields: Object.fromEntries(entity.fields.map(field => [field.name, {
        type: field.type,
        many: Boolean(field.many),
        required: Boolean(field.required),
        upload: field.upload || null
      }]))
    }
  ]));

  const lines = [
    "'use strict';", '',
    "const crypto = require('node:crypto');",
    "const path = require('node:path');",
    "const fs = require('node:fs');",
    "const fsp = require('node:fs/promises');",
    "const multer = require('multer');",
    ...(spec.storage.provider === 's3' ? [
      "const {S3Client, PutObjectCommand, GetObjectCommand, DeleteObjectCommand} = require('@aws-sdk/client-s3');",
      "const {getSignedUrl} = require('@aws-sdk/s3-request-presigner');"
    ] : []),
    '',
    'const config = ' + js(spec.storage) + ';',
    'const definitions = ' + js(definitions) + ';',
    'const localRoot = path.resolve(process.cwd(), config.local.directory);',
    'let s3Client = null;',
    '',
    'function storageError(message, statusCode = 400) { const error = new Error(message); error.statusCode = statusCode; return error; }',
    'function safeKey(raw) {',
    '  const value = String(raw || "").split(String.fromCharCode(92)).join("/");',
    '  const normalized = path.posix.normalize(value).replace(/^\\/+/, "");',
    '  if (!normalized || normalized === "." || normalized.startsWith("../") || normalized.includes("/../")) throw storageError("Invalid storage key");',
    '  return normalized;',
    '}',
    'function localPath(key) {',
    '  const target = path.resolve(localRoot, safeKey(key));',
    '  if (target !== localRoot && !target.startsWith(localRoot + path.sep)) throw storageError("Invalid storage path");',
    '  return target;',
    '}',
    'function mimeMatches(allowed, actual) {',
    '  return allowed.some(pattern => pattern === "*/*" || pattern === actual || (pattern.endsWith("/*") && actual.startsWith(pattern.slice(0, -1))));',
    '}',
    'function fileDefinitions(entityName) {',
    '  const entity = definitions[entityName];',
    '  if (!entity) throw storageError("Unknown upload entity");',
    '  return Object.fromEntries(Object.entries(entity.fields).filter(([, field]) => field.type === "file"));',
    '}',
    'function extensionFor(name, preserve) {',
    '  if (!preserve) return "";',
    '  const ext = path.extname(String(name || "")).toLowerCase();',
    '  return /^[.][a-z0-9]{1,12}$/.test(ext) ? ext : "";',
    '}',
    'function keyFor(entityName, fieldName, definition, file) {',
    '  const directory = safeKey(definition.upload.directory || (entityName.toLowerCase() + "/" + fieldName));',
    '  return path.posix.join(directory, crypto.randomUUID() + extensionFor(file.originalname, definition.upload.preserveExtension));',
    '}',
    'function checksum(buffer) { return crypto.createHash("sha256").update(buffer).digest("hex"); }',
    '',
    ...(spec.storage.provider === 's3' ? [
      'function client() {',
      '  if (s3Client) return s3Client;',
      '  const options = {region: process.env[config.s3.regionEnv], forcePathStyle: config.s3.forcePathStyle};',
      '  if (config.s3.endpointEnv && process.env[config.s3.endpointEnv]) options.endpoint = process.env[config.s3.endpointEnv];',
      '  if (config.s3.accessKeyEnv && config.s3.secretKeyEnv && process.env[config.s3.accessKeyEnv] && process.env[config.s3.secretKeyEnv]) {',
      '    options.credentials = {accessKeyId: process.env[config.s3.accessKeyEnv], secretAccessKey: process.env[config.s3.secretKeyEnv]};',
      '  }',
      '  s3Client = new S3Client(options);',
      '  return s3Client;',
      '}',
      'function bucket() { const value = process.env[config.s3.bucketEnv]; if (!value) throw storageError("Missing S3 bucket", 500); return value; }',
      ''
    ] : []),
    'async function putFile(entityName, fieldName, definition, file) {',
    '  const key = keyFor(entityName, fieldName, definition, file);',
    ...(spec.storage.provider === 'local' ? [
      '  const target = localPath(key);',
      '  await fsp.mkdir(path.dirname(target), {recursive: true});',
      '  await fsp.writeFile(target, file.buffer, {flag: "wx"});'
    ] : [
      '  await client().send(new PutObjectCommand({Bucket: bucket(), Key: key, Body: file.buffer, ContentType: file.mimetype}));'
    ]),
    '  return {',
    '    key, originalName: file.originalname, mimeType: file.mimetype, size: file.size,',
    '    checksumSha256: checksum(file.buffer), provider: config.provider, uploadedAt: new Date().toISOString()',
    '  };',
    '}',
    'async function deleteMetadata(metadata) {',
    '  if (!metadata || typeof metadata !== "object" || !metadata.key) return;',
    '  const key = safeKey(metadata.key);',
    '  if (metadata.provider && metadata.provider !== config.provider) return;',
    ...(spec.storage.provider === 'local' ? [
      '  try { await fsp.unlink(localPath(key)); } catch (error) { if (error.code !== "ENOENT") throw error; }'
    ] : [
      '  await client().send(new DeleteObjectCommand({Bucket: bucket(), Key: key}));'
    ]),
    '}',
    'async function cleanup(values) {',
    '  for (const value of values || []) {',
    '    if (Array.isArray(value)) await cleanup(value);',
    '    else await deleteMetadata(value);',
    '  }',
    '}',
    '',
    'function parseText(definition, value) {',
    '  if (value === undefined) return value;',
    '  if (definition.type === "number") { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : value; }',
    '  if (definition.type === "boolean") { if (value === "true") return true; if (value === "false") return false; return value; }',
    '  if (definition.type === "reference" && definition.many) {',
    '    try { const parsed = JSON.parse(value); if (Array.isArray(parsed)) return parsed; } catch {}',
    '    return String(value).split(",").map(item => item.trim()).filter(Boolean);',
    '  }',
    '  if (definition.type === "file" && value === "null") return null;',
    '  return value;',
    '}',
    'function normalizeBody(entityName, req) {',
    '  const entity = definitions[entityName];',
    '  req.body = req.body || {};',
    '  for (const [name, definition] of Object.entries(entity.fields)) {',
    '    if (!Object.prototype.hasOwnProperty.call(req.body, name)) continue;',
    '    req.body[name] = parseText(definition, req.body[name]);',
    '  }',
    '}',
    'function sanitizeNonMultipart(entityName, req) {',
    '  const fields = fileDefinitions(entityName);',
    '  req.body = req.body || {};',
    '  for (const [name, definition] of Object.entries(fields)) {',
    '    const value = req.body[name];',
    '    const clearMany = definition.many && Array.isArray(value) && value.length === 0;',
    '    if (value !== null && !clearMany) delete req.body[name];',
    '  }',
    '}',
    '',
    'function uploadMiddleware(entityName) {',
    '  const fields = fileDefinitions(entityName);',
    '  const entries = Object.entries(fields);',
    '  if (!entries.length) return (req, res, next) => next();',
    '  const maxBytes = Math.max(...entries.map(([, field]) => field.upload.maxBytes));',
    '  const parser = multer({',
    '    storage: multer.memoryStorage(),',
    '    limits: {fileSize: maxBytes, files: entries.reduce((sum, [, field]) => sum + (field.many ? 20 : 1), 0)},',
    '    fileFilter(req, file, callback) {',
    '      const definition = fields[file.fieldname];',
    '      if (!definition) return callback(storageError("Unexpected file field: " + file.fieldname));',
    '      if (!mimeMatches(definition.upload.mimeTypes, file.mimetype)) return callback(storageError("Unsupported MIME type for " + file.fieldname));',
    '      callback(null, true);',
    '    }',
    '  }).fields(entries.map(([name, field]) => ({name, maxCount: field.many ? 20 : 1})));',
    '',
    '  return function parseMultipart(req, res, next) {',
    '    if (!req.is("multipart/form-data")) { sanitizeNonMultipart(entityName, req); return next(); }',
    '    parser(req, res, async error => {',
    '      if (error) return res.status(error.statusCode || 400).json({error: error.message});',
    '      const stored = [];',
    '      try {',
    '        normalizeBody(entityName, req);',
    '        for (const [fieldName, definition] of entries) {',
    '          const files = req.files && req.files[fieldName] || [];',
    '          for (const file of files) {',
    '            if (file.size > definition.upload.maxBytes) throw storageError(fieldName + " exceeds maxBytes");',
    '            if (!mimeMatches(definition.upload.mimeTypes, file.mimetype)) throw storageError("Unsupported MIME type for " + fieldName);',
    '          }',
    '          if (!files.length) continue;',
    '          const metadata = [];',
    '          for (const file of files) { const saved = await putFile(entityName, fieldName, definition, file); metadata.push(saved); stored.push(saved); }',
    '          req.body[fieldName] = definition.many ? metadata : metadata[0];',
    '        }',
    '        req.j2eStoredUploads = stored;',
    '        req.j2eUploadsCommitted = false;',
    '        res.once("finish", () => { if (!req.j2eUploadsCommitted && stored.length) cleanup(stored).catch(() => {}); });',
    '        next();',
    '      } catch (uploadError) {',
    '        await cleanup(stored).catch(() => {});',
    '        res.status(uploadError.statusCode || 400).json({error: uploadError.message});',
    '      }',
    '    });',
    '  };',
    '}',
    '',
    'function commitUploads(req) { if (req) req.j2eUploadsCommitted = true; }',
    'function metadataKeys(value) {',
    '  const items = Array.isArray(value) ? value : (value ? [value] : []);',
    '  return new Set(items.filter(item => item && item.key).map(item => item.key));',
    '}',
    'async function cleanupReplaced(entityName, existing, input) {',
    '  if (!existing || !input) return;',
    '  const plain = typeof existing.toObject === "function" ? existing.toObject() : existing;',
    '  for (const [name] of Object.entries(fileDefinitions(entityName))) {',
    '    if (!Object.prototype.hasOwnProperty.call(input, name)) continue;',
    '    const keep = metadataKeys(input[name]);',
    '    const oldValues = Array.isArray(plain[name]) ? plain[name] : (plain[name] ? [plain[name]] : []);',
    '    await cleanup(oldValues.filter(item => !keep.has(item && item.key)));',
    '  }',
    '}',
    'async function cleanupEntity(entityName, value) {',
    '  if (!value) return;',
    '  const plain = typeof value.toObject === "function" ? value.toObject() : value;',
    '  for (const name of Object.keys(fileDefinitions(entityName))) await cleanup(Array.isArray(plain[name]) ? plain[name] : [plain[name]]);',
    '}',
    '',
    'function localToken(metadata) {',
    '  const expiresAt = Math.floor(Date.now() / 1000) + config.signedUrls.expiresSeconds;',
    '  const payload = Buffer.from(JSON.stringify({key: safeKey(metadata.key), mimeType: metadata.mimeType, originalName: metadata.originalName, exp: expiresAt})).toString("base64url");',
    '  const secret = process.env[config.signedUrls.signingSecretEnv];',
    '  if (!secret) throw storageError("Missing file signing secret", 500);',
    '  const signature = crypto.createHmac("sha256", secret).update(payload).digest("base64url");',
    '  return payload + "." + signature;',
    '}',
    'function verifyLocalToken(token) {',
    '  const parts = String(token || "").split(".");',
    '  if (parts.length !== 2) throw storageError("Invalid file token", 403);',
    '  const secret = process.env[config.signedUrls.signingSecretEnv];',
    '  if (!secret) throw storageError("Missing file signing secret", 500);',
    '  const expected = crypto.createHmac("sha256", secret).update(parts[0]).digest();',
    '  const actual = Buffer.from(parts[1], "base64url");',
    '  if (expected.length !== actual.length || !crypto.timingSafeEqual(expected, actual)) throw storageError("Invalid file token", 403);',
    '  let payload; try { payload = JSON.parse(Buffer.from(parts[0], "base64url").toString("utf8")); } catch { throw storageError("Invalid file token", 403); }',
    '  if (!payload.exp || payload.exp < Math.floor(Date.now() / 1000)) throw storageError("Expired file token", 403);',
    '  payload.key = safeKey(payload.key);',
    '  return payload;',
    '}',
    '',
    'async function signedUrl(metadata, req) {',
    '  if (!metadata || !metadata.key || !config.signedUrls.enabled) return null;',
    '  safeKey(metadata.key);',
    ...(spec.storage.provider === 'local' ? [
      '  const token = localToken(metadata);',
      '  const relative = config.signedUrls.path.replace(":token", encodeURIComponent(token));',
      '  if (!req) return relative;',
      '  return req.protocol + "://" + req.get("host") + relative;'
    ] : [
      '  return getSignedUrl(client(), new GetObjectCommand({Bucket: bucket(), Key: safeKey(metadata.key)}), {expiresIn: config.signedUrls.expiresSeconds});'
    ]),
    '}',
    'async function enrichMetadata(metadata, req) {',
    '  if (!metadata || typeof metadata !== "object" || !metadata.key) return metadata;',
    '  return {...metadata, url: await signedUrl(metadata, req)};',
    '}',
    'async function enrich(entityName, value, req) {',
    '  if (value === null || value === undefined) return value;',
    '  if (Array.isArray(value)) return Promise.all(value.map(item => enrich(entityName, item, req)));',
    '  const plain = typeof value.toObject === "function" ? value.toObject() : {...value};',
    '  for (const [name, definition] of Object.entries(fileDefinitions(entityName))) {',
    '    if (plain[name] === undefined || plain[name] === null) continue;',
    '    plain[name] = definition.many',
    '      ? await Promise.all((plain[name] || []).map(item => enrichMetadata(item, req)))',
    '      : await enrichMetadata(plain[name], req);',
    '  }',
    '  return plain;',
    '}',
    '',
    'async function downloadHandler(req, res, next) {',
    '  try {',
    ...(spec.storage.provider === 'local' ? [
      '    const metadata = verifyLocalToken(req.params.token);',
      '    const target = localPath(metadata.key);',
      '    try { await fsp.access(target); } catch (error) {',
      '      if (error && error.code === "ENOENT") return res.status(404).json({error: "File not found"});',
      '      throw error;',
      '    }',
      '    res.setHeader("Content-Type", metadata.mimeType || "application/octet-stream");',
      '    res.setHeader("Content-Disposition", "inline; filename*=UTF-8\'\'" + encodeURIComponent(metadata.originalName || path.basename(metadata.key)));',
      '    const stream = fs.createReadStream(target);',
      '    stream.on("error", error => {',
      '      if (!res.headersSent && error && error.code === "ENOENT") return res.status(404).json({error: "File not found"});',
      '      next(error);',
      '    });',
      '    stream.pipe(res);'
    ] : [
      '    return res.status(404).json({error: "Signed S3 URLs are returned directly"});'
    ]),
    '  } catch (error) { next(error); }',
    '}',
    '',
        'async function parseFastifyMultipart(entityName, request) {',
    '  const fields = fileDefinitions(entityName);',
    '  const entries = Object.entries(fields);',
    '  if (!entries.length) return {body: request.body || {}, stored: []};',
    '  if (!request.isMultipart()) {',
    '    const req = {body: {...(request.body || {})}};',
    '    sanitizeNonMultipart(entityName, req);',
    '    normalizeBody(entityName, req);',
    '    return {body: req.body, stored: []};',
    '  }',
    '  const body = {};',
    '  const stored = [];',
    '  const counts = {};',
    '  const maxBytes = Math.max(...entries.map(([, field]) => field.upload.maxBytes));',
    '  try {',
    '    for await (const part of request.parts({limits: {fileSize: maxBytes, files: entries.reduce((n, [, field]) => n + (field.many ? 20 : 1), 0)}})) {',
    '      if (part.type !== "file") {body[part.fieldname] = part.value; continue;}',
    '      const definition = fields[part.fieldname];',
    '      if (!definition) throw storageError("Unexpected file field: " + part.fieldname);',
    '      counts[part.fieldname] = (counts[part.fieldname] || 0) + 1;',
    '      if (counts[part.fieldname] > (definition.many ? 20 : 1)) throw storageError("Too many files for " + part.fieldname);',
    '      if (!mimeMatches(definition.upload.mimeTypes, part.mimetype)) throw storageError("Unsupported MIME type for " + part.fieldname);',
    '      const buffer = await part.toBuffer();',
    '      if (part.file.truncated || buffer.length > definition.upload.maxBytes) throw storageError(part.fieldname + " exceeds maxBytes");',
    '      const metadata = await putFile(entityName, part.fieldname, definition, {buffer, size: buffer.length, originalname: part.filename, mimetype: part.mimetype});',
    '      stored.push(metadata);',
    '      if (definition.many) (body[part.fieldname] ||= []).push(metadata);',
    '      else body[part.fieldname] = metadata;',
    '    }',
    '    const req = {body};',
    '    normalizeBody(entityName, req);',
    '    return {body: req.body, stored};',
    '  } catch (error) {',
    '    if (error.statusCode === 413 || error.code === "FST_REQ_FILE_TOO_LARGE") error.statusCode = 400;',
    '    await cleanup(stored).catch(() => {});',
    '    throw error;',
    '  }',
    '}',
    '',
    'async function fastifyDownload(request, reply) {',
    ...(spec.storage.provider === 'local' ? [
      '  const metadata = verifyLocalToken(request.params.token);',
      '  const target = localPath(metadata.key);',
      '  try {await fsp.access(target);} catch (error) {if (error.code === "ENOENT") return reply.code(404).send({error: "File not found"}); throw error;}',
      '  reply.header("Content-Type", metadata.mimeType || "application/octet-stream");',
      '  reply.header("Content-Disposition", "inline; filename*=UTF-8" + String.fromCharCode(39, 39) + encodeURIComponent(metadata.originalName || path.basename(metadata.key)));',
      '  return reply.send(fs.createReadStream(target));'
    ] : ['  return reply.code(404).send({error: "Signed S3 URLs are returned directly"});']),
    '}',
    'module.exports = {uploadMiddleware, parseFastifyMultipart, commitUploads, cleanup, cleanupReplaced, cleanupEntity, enrich, signedUrl, downloadHandler, fastifyDownload};',
    ''
  ];
  return lines.join('\n');
};
