'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

module.exports = function workflowEngineSource(spec) {
  const enginePath = filePaths(spec).workflowEngine;
  const imports = spec.entities.map(entity =>
    'const ' + entity.name + ' = require(' + js(relativeRequire(enginePath, filePaths(spec, entity.name).model)) + ');'
  );
  const models = '{' + spec.entities.map(entity => entity.name).join(', ') + '}';

  return [
    "'use strict';", '',
    "const mongoose = require('mongoose');",
    ...imports,
    'const eventBus = require(' + js(relativeRequire(enginePath, filePaths(spec).eventBus)) + ');', '',
    'const workflows = ' + js(Object.fromEntries(spec.workflows.map(workflow => [workflow.name, workflow]))) + ';',
    'const models = ' + models + ';', '',
    'function readPath(root, parts) {',
    '  let value = root;',
    '  for (const part of parts) {',
    '    if (value === null || value === undefined) return undefined;',
    '    value = value[part];',
    '  }',
    '  return value;',
    '}', '',
    'function resolveString(value, context) {',
    '  if (!value.startsWith("$")) return value;',
    '  if (value.startsWith("$$")) return value.slice(1);',
    '  const parts = value.split(".");',
    '  const root = parts.shift();',
    '  if (root === "$body") return readPath(context.body, parts);',
    '  if (root === "$params") return readPath(context.params, parts);',
    '  if (root === "$query") return readPath(context.query, parts);',
    '  if (root === "$auth") return readPath(context.auth, parts);',
    '  if (root === "$steps") {',
    '    const step = parts.shift();',
    '    return readPath(context.steps[step], parts);',
    '  }',
    '  return undefined;',
    '}', '',
    'function resolve(value, context) {',
    '  if (typeof value === "string") return resolveString(value, context);',
    '  if (Array.isArray(value)) return value.map(item => resolve(item, context));',
    '  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, resolve(item, context)]));',
    '  return value;',
    '}', '',
    'async function executeDatabaseStep(step, context, session) {',
    '  const model = models[step.entity];',
    '  if (step.action === "findById") {',
    '    let query = model.findById(resolve(step.id, context));',
    '    if (session) query = query.session(session);',
    '    return query;',
    '  }',
    '  if (step.action === "create") {',
    '    const items = await model.create([resolve(step.data, context)], session ? {session} : {});',
    '    return items[0];',
    '  }',
    '  if (step.action === "updateById") {',
    '    let query = model.findByIdAndUpdate(resolve(step.id, context), resolve(step.data, context), {new: true, runValidators: true});',
    '    if (session) query = query.session(session);',
    '    return query;',
    '  }',
    '  if (step.action === "deleteById") {',
    '    let query = model.findByIdAndDelete(resolve(step.id, context));',
    '    if (session) query = query.session(session);',
    '    return query;',
    '  }',
    '}', '',
    'async function runSteps(workflow, context, session) {',
    '  let lastResult = null;',
    '  for (const step of workflow.steps) {',
    '    let result;',
    '    if (["findById", "create", "updateById", "deleteById"].includes(step.action)) {',
    '      result = await executeDatabaseStep(step, context, session);',
    '    } else if (step.action === "emit") {',
    '      result = resolve(step.payload, context);',
    '      context.pendingEvents.push({name: step.event, payload: result});',
    '    } else if (step.action === "respond") {',
    '      result = {__response: true, status: step.status, body: resolve(step.body, context)};',
    '    }',
    '    context.steps[step.name] = result;',
    '    lastResult = result;',
    '    if (result && result.__response) break;',
    '  }',
    '  return lastResult;',
    '}', '',
    'async function execute(name, req) {',
    '  const workflow = workflows[name];',
    "  if (!workflow) throw new Error('Unknown workflow: ' + name);",
    '  const context = {body: req.body || {}, params: req.params || {}, query: req.query || {}, auth: req.auth || {}, steps: {}, pendingEvents: []};',
    '  let result;',
    '  if (workflow.transaction) {',
    '    const session = await mongoose.startSession();',
    '    try {',
    '      await session.withTransaction(async () => { result = await runSteps(workflow, context, session); });',
    '    } finally { await session.endSession(); }',
    '  } else {',
    '    result = await runSteps(workflow, context, null);',
    '  }',
    '  for (const event of context.pendingEvents) await eventBus.publish(event.name, event.payload);',
    '  return {result, steps: context.steps};',
    '}', '',
    'module.exports = {execute, resolve};', ''
  ].join('\n');
};
