'use strict';

const {filePaths, js, relativeRequire} = require('./utils');

module.exports = function workerSource(spec) {
  const paths = filePaths(spec);
  return [
    "'use strict';", '',
    "require('dotenv').config();",
    'const validateEnvironment = require(' + js(relativeRequire(paths.worker, paths.environment)) + ');',
    'const connectDatabase = require(' + js(relativeRequire(paths.worker, paths.database)) + ');',
    'const outbox = require(' + js(relativeRequire(paths.worker, paths.outbox)) + ');',
    'const events = require(' + js(relativeRequire(paths.worker, paths.eventBus)) + ');',
    'const workflows = require(' + js(relativeRequire(paths.worker, paths.workflowEngine)) + ');',
    ...(spec.observability.enabled ? ['const observability = require(' + js(relativeRequire(paths.worker, paths.observability)) + ');'] : []),
    ...(spec.cache.enabled ? ['const cache = require(' + js(relativeRequire(paths.worker, paths.cache)) + ');'] : []), '',
    'const jobs = ' + js(spec.jobs) + ';',
    'const selectedQueues = (process.env.J2E_WORKER_QUEUES || "").split(",").map(value => value.trim()).filter(Boolean);',
    'let stopped = false;', '',
    'async function processRecord(record) {',
    '  if (record.kind === "event") return events.deliver(record.name, record.payload);',
    '  if (record.kind === "job") {',
    '    const job = jobs[record.name];',
    '    if (!job) throw new Error("Unknown job: " + record.name);',
    '    const recordId = record.id || record._id;',
    '    return workflows.execute(job.workflow, {',
    '      body: record.payload || {}, params: {}, query: {}, auth: {},',
    '      job: {id: String(recordId), attempts: record.attempts}',
    '    });',
    '  }',
    '  throw new Error("Unsupported outbox record kind: " + record.kind);',
    '}', '',
    'async function processBatch() {',
    '  await outbox.recoverStale();',
    '  let processed = 0;',
    '  while (processed < ' + spec.outbox.batchSize + ') {',
    '    const record = await outbox.claimNext(selectedQueues);',
    '    if (!record) break;',
    '    try {',
    ...(spec.observability.enabled
      ? ['      await observability.instrumentWorkerRecord(record, () => processRecord(record));']
      : ['      await processRecord(record);']),
    '      await outbox.markDone(record);',
    '    } catch (error) {',
    '      await outbox.markFailed(record, error);',
    '    }',
    '    processed += 1;',
    '  }',
    '  return processed;',
    '}', '',
    'async function startWorker() {',
    '  stopped = false;',
    '  while (!stopped) {',
    '    const processed = await processBatch();',
    '    if (processed === 0) await new Promise(resolve => setTimeout(resolve, ' + spec.outbox.pollIntervalMs + '));',
    '  }',
    '}', '',
    'function stopWorker() { stopped = true; }', '',
    'async function main() {',
    '  validateEnvironment();',
    ...(spec.observability.enabled ? ['  await observability.startTracing();'] : []),
    '  await connectDatabase();',
    '  for (const signal of ["SIGTERM", "SIGINT"]) process.once(signal, stopWorker);',
    '  try {',
    '    if (process.argv.includes("--retry-dead")) { console.log("Retried dead outbox records:", await outbox.retryDead()); return; }',
    '    if (process.argv.includes("--once")) { await processBatch(); return; }',
    '    await startWorker();',
    '  } finally {',
    ...(spec.cache.enabled ? ['    await cache.disconnect();'] : []),
    '    if (connectDatabase.disconnect) await connectDatabase.disconnect();'
    ...(spec.observability.enabled ? ['    await observability.shutdownTracing();'] : []),
    '  }',
    '}', '',
    'if (require.main === module) {',
    ...(spec.observability.enabled
      ? ['  main().catch(error => { observability.logger.error("worker.failed", {error: error.message}); process.exitCode = 1; });']
      : ['  main().catch(error => { console.error("Worker failed:", error); process.exitCode = 1; });']),
    '}', '',
    'module.exports = {processBatch, processRecord, startWorker, stopWorker};', ''
  ].join('\n');
};
