'use strict';

const {validateSpec} = require('./validate-spec');

const DEFAULT_OPERATIONS = {
  list: {enabled: true, method: 'get', path: '/', status: 200, lean: true},
  get: {enabled: true, method: 'get', path: '/:id', status: 200, notFoundStatus: 404, lean: true},
  create: {enabled: true, method: 'post', path: '/', status: 201},
  update: {enabled: true, method: 'patch', path: '/:id', status: 200, notFoundStatus: 404, runValidators: true},
  delete: {enabled: true, method: 'delete', path: '/:id', status: 204, notFoundStatus: 404}
};

function pluralize(value) {
  if (/[^aeiou]y$/i.test(value)) return value.slice(0, -1) + 'ies';
  if (/(s|x|z|ch|sh)$/i.test(value)) return value + 'es';
  return value + 's';
}

function defaultRoute(entityName) {
  return pluralize(entityName.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase());
}

function packageName(value) {
  return String(value).trim().toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'generated-express-app';
}

function normalizePrefix(value) {
  if (value === '/') return '';
  return value.replace(/\/$/, '');
}

function normalizeOperation(name, value, idParam) {
  const defaults = {...DEFAULT_OPERATIONS[name]};
  if (defaults.path.includes(':id') && idParam !== 'id') defaults.path = defaults.path.replace(':id', ':' + idParam);
  if (typeof value === 'boolean') return {...defaults, enabled: value};
  return {...defaults, ...(value || {})};
}

function normalizeSpec(spec) {
  validateSpec(spec);

  const packageConfig = spec.app.package || {};
  const health = spec.app.health || {};
  const responses = spec.app.responses || {};
  const statusCodes = spec.app.statusCodes || {};

  return {
    generation: {
      outputDir: spec.generation && spec.generation.outputDir
    },
    app: {
      name: spec.app.name.trim(),
      port: spec.app.port || 3000,
      portEnv: spec.app.portEnv || 'PORT',
      apiPrefix: normalizePrefix(spec.app.apiPrefix || '/api'),
      bodyLimit: spec.app.bodyLimit === undefined ? '1mb' : spec.app.bodyLimit,
      health: {
        enabled: health.enabled !== false,
        path: health.path || '/health',
        status: health.status || 200,
        response: health.response === undefined ? {status: 'ok'} : health.response
      },
      responses: {
        notFound: responses.notFound || 'Route not found',
        validationError: responses.validationError || 'Validation failed',
        invalidIdentifier: responses.invalidIdentifier || 'Invalid identifier',
        uniqueConstraint: responses.uniqueConstraint || 'Unique constraint violated',
        internalError: responses.internalError || 'Internal server error'
      },
      statusCodes: {
        notFound: statusCodes.notFound || 404,
        validationError: statusCodes.validationError || 400,
        invalidIdentifier: statusCodes.invalidIdentifier || 400,
        uniqueConstraint: statusCodes.uniqueConstraint || 409,
        internalError: statusCodes.internalError || 500
      },
      package: {
        name: packageConfig.name || packageName(spec.app.name),
        version: packageConfig.version || '0.1.0',
        private: packageConfig.private !== false,
        description: packageConfig.description || 'Generated by json-to-express',
        nodeEngine: packageConfig.nodeEngine || '>=18',
        scripts: {
          start: 'node src/server.js',
          dev: 'node --watch src/server.js',
          test: 'node --test',
          ...(packageConfig.scripts || {})
        },
        dependencies: {
          dotenv: '^16.4.5',
          express: '^4.21.1',
          mongoose: '^8.8.0',
          ...(packageConfig.dependencies || {})
        },
        devDependencies: {
          supertest: '^7.0.0',
          ...(packageConfig.devDependencies || {})
        }
      }
    },
    database: {
      type: 'mongodb',
      uriEnv: spec.database.uriEnv || 'MONGODB_URI',
      defaultUri: spec.database.defaultUri || 'mongodb://127.0.0.1:27017/' + (packageConfig.name || packageName(spec.app.name)),
      options: spec.database.options || {}
    },
    entities: Object.entries(spec.entities).map(([name, entity]) => {
      const idParam = entity.idParam || 'id';
      const operations = {};
      for (const operationName of Object.keys(DEFAULT_OPERATIONS)) {
        operations[operationName] = normalizeOperation(
          operationName,
          entity.operations && entity.operations[operationName],
          idParam
        );
      }

      return {
        name,
        route: entity.route || defaultRoute(name),
        collection: entity.collection,
        idParam,
        schemaOptions: {
          timestamps: true,
          versionKey: false,
          ...(entity.schemaOptions || {})
        },
        operations,
        fields: Object.entries(entity.fields).map(([fieldName, field]) => ({
          name: fieldName,
          type: field.type,
          required: field.required,
          unique: field.unique,
          enum: field.enum,
          min: field.min,
          max: field.max,
          minLength: field.minLength,
          maxLength: field.maxLength,
          default: field.default,
          options: field.options || {}
        }))
      };
    })
  };
}

module.exports = {defaultRoute, normalizeSpec, packageName, pluralize};
